### PR TITLE
Fixes usage links in USING_ADVANCED.md

### PR DESCRIPTION
**Pull request by wraith13**
Just fixes link path in document.

### CODE REVIEW

**Comment by styfle** [comment]
@UziTech I think it might be easier to merge my branch first and then @wraith13 can open a new PR against the new master. Are you both okay with this?

**Comment by wraith13** [comment]
What does "new master" mean?
I can see only one branch named master.

Because my English is not good, I may misunderstand something.
You can do it on your own.

**Comment by styfle** [comment]
@wraith13 Sorry, I didn't communicate that well.

We just merged #1138 which moved this file from `USING_ADVANCED.md` to `/docs/USING_ADVANCED.md`. You can see this change in the `master` branch now which is why GitHub shows the message `This branch has conflicts that must be resolved`. 

So you can either rebase this branch on master, or create a new branch from the latest master.

Thanks! 👍

**Comment by wraith13** [comment]
I see. I will do it.

**Comment by wraith13** [comment]
https://github.com/markedjs/marked/pull/1151
I did it.

**Pull request closed without merging**
