### PR TITLE
revert 2841

### LINKED ISSUE #2865: Improper emoji rendering with v5.1.0
**Marked version:** v5.1.0

**Describe the bug**
Emoji rendering fails if located at the beginning or the end of a bold text.

I don't know if this is specific to the bold markup or if the issue happens with other markup.

**To Reproduce**

Here's a markdown text to reproduce the issue:
```markdown
Situations where it fails:

**test 💁**

**💁 test**

**🤓 test**

**🏖️ test**

Situations where it works:

**💁 **

**⚠️ test**

Here, the emoji rendering works, but the text doesn't get rendered in italic.

*💁 test*
```

The text above [on Markded Demo](https://marked.js.org/demo/?text=Situations%20where%20it%20fails%3A%0A%0A**test%20%F0%9F%92%81**%0A%0A**%F0%9F%92%81%20test**%0A%0A**%F0%9F%A4%93%20test**%0A%0A**%F0%9F%8F%96%EF%B8%8F%20test**%0A%0ASituations%20where%20it%20works%3A%0A%0A**%F0%9F%92%81%20**%0A%0A**%E2%9A%A0%EF%B8%8F%20test**%0A%0AHere%2C%20the%20emoji%20rendering%20works%2C%20but%20the%20text%20doesn%27t%20get%20rendered%20in%20italic.%0A%0A*%F0%9F%92%81%20test*%0A%0A&options=%7B%0A%20%22async%22%3A%20false%2C%0A%20%22baseUrl%22%3A%20null%2C%0A%20%22breaks%22%3A%20false%2C%0A%20%22extensions%22%3A%20null%2C%0A%20%22gfm%22%3A%20true%2C%0A%20%22headerIds%22%3A%20true%2C%0A%20%22headerPrefix%22%3A%20%22%22%2C%0A%20%22highlight%22%3A%20null%2C%0A%20%22hooks%22%3A%20null%2C%0A%20%22langPrefix%22%3A%20%22language-%22%2C%0A%20%22mangle%22%3A%20true%2C%0A%20%22pedantic%22%3A%20false%2C%0A%20%22sanitize%22%3A%20false%2C%0A%20%22sanitizer%22%3A%20null%2C%0A%20%22silent%22%3A%20false%2C%0A%20%22smartypants%22%3A%20false%2C%0A%20%22tokenizer%22%3A%20null%2C%0A%20%22walkTokens%22%3A%20null%2C%0A%20%22xhtml%22%3A%20false%0A%7D&version=5.1.0) and [on CommonMark Demo](https://spec.commonmark.org/dingus/?text=Situations%20where%20it%20fails%3A%0A%0A**test%20%F0%9F%92%81**%0A%0A**%F0%9F%92%81%20test**%0A%0A**%F0%9F%A4%93%20test**%0A%0A**%F0%9F%8F%96%EF%B8%8F%20test**%0A%0ASituations%20where%20it%20works%3A%0A%0A**%F0%9F%92%81%20**%0A%0A**%E2%9A%A0%EF%B8%8F%20test**%0A%0AHere%2C%20the%20emoji%20rendering%20works%2C%20but%20the%20text%20doesn%27t%20get%20rendered%20in%20italic.%0A%0A*%F0%9F%92%81%20test*%0A%0A)

Screenshot of the rendering on Marked Demo:
Screenshot 2023-07-03 at 17 33 19

**Expected behavior**

What is rendered on CommonMark Demo:
Screenshot 2023-07-03 at 17 37 48

### PR DESCRIPTION
**Pull request by UziTech**
**Marked version:** 5.1.1

## Description

Revert #2841

- Fixes #2865

## Contributor

- [x] Test(s) exist to ensure functionality and minimize regression (if no tests added, list tests covering this PR); or,
- [ ] no tests required for this PR.
- [ ] If submitting new feature, it has been documented in the appropriate places.

## Committer

In most cases, this should be a different person than the contributor.

- [ ] CI is green (no forced merge required).
- [ ] Squash and Merge PR following [conventional commit guidelines](https://www.conventionalcommits.org/).

### CODE REVIEW

**Comment by calculuschild** [comment]
Let me play with it first. I suspect it's not \p{P} but my changes to the Lexer masking step.

**Comment by calculuschild** [comment]
Mmmm.... I have found the issue. Making it work is a bit obnoxious, but I managed to do it. I can share an alternative PR in a bit with my changes, although the workaround looks a bit odd.

The issue is that we need to use RegEx in unicode mode (u), to process `\p{P}`. In unicode mode, the RegEx also treats multi-char emojis as single unicode characters, so "💁" for example is counted as a single character instead of string of 2 unicode chars. This throws off string lengths for slicing at multiple points (particularly using `match.index`.

Essentially, the solution is to destructure the string into an array and slice on the array instead, since this preserves unicode chars:

```
const raw = src.slice(0, lLength + match.index + rLength + 1);

     becomes

const raw = [...src].slice(0, lLength + match.index + rLength + 1).join('');
```

 Speed-wise, it seems the same to me, so the tradeoff looks like:

##### Pros: 
* more complete coverage of all punctuation chars
* simpler regex rule
 
##### Cons:
* Odd handling of string slicing in the emStrong tokenizer

**Comment by UziTech** [comment]
Nice catch! I would rather fix the problem than revert. I'll wait for your fix.

**Comment by calculuschild** [comment]
Apologies. I kind of forgot about this. New PR here: #2942

**Pull request closed without merging**
