### PR TITLE
Testing options and defaults

### PR DESCRIPTION
**Pull request by joshbruce**
**Marked version:** 0.3.19

**Markdown flavor:** n/a

## Description

PR tests Marked configuration options. Related to #1160. 

## Expectation

- `marked.options` to be defined.

## Result

- `marked.options` is undefined. Can be set with `marked.defaults` or passing directly to the renderer (??).

## What was attempted

See tests.

## Contributor

- [x] Test(s) exist to ensure functionality and minimize regression (if no tests added, list tests covering this PR); or,
- [ ] no tests required for this PR.
- [ ] If submitting new feature, it has been documented in the appropriate places.

## Committer

In most cases, this should be a different person than the contributor.

- [ ] Draft GitHub release notes have been updated.
- [ ] CI is green (no forced merge required).
- [ ] Merge PR

### CODE REVIEW

**Comment by joshbruce** [comment]
Also, it appears Jasmine might be holding onto `marked` as a singleton across all tests?? I tried a couple of naive attempts at resolving but figured it would be easier to just ask the question.

**Comment by joshbruce** [comment]
Believe NodeJS is trying to use Marked as a singleton. Going add `afterEach` and `beforeEach`.

**Comment by styfle** [comment]
When you say `require('marked')` you get the object back.

See the [node.js docs](https://nodejs.org/docs/latest/api/modules.html#modules_caching) for more info.

**Comment by joshbruce** [comment]
Given my new knowledge, not sure this needs to stick around. If this is common knowledge in the JS community, then the tests don't add anything to the edification of library consumers. Closing.

**Pull request closed without merging**
