### PR TITLE
Add Homebrew install to readme

### PR DESCRIPTION
**Pull request by SeekingMeaning**
**Marked version:** 1.1.0

**Markdown flavor:** n/a

## Description

- Fixes #### (if fixing a known issue; otherwise, describe issue using the following format)

## Contributor

- [ ] Test(s) exist to ensure functionality and minimize regression (if no tests added, list tests covering this PR); or,
- [x] no tests required for this PR.
- [ ] If submitting new feature, it has been documented in the appropriate places.

## Committer

In most cases, this should be a different person than the contributor.

- [ ] Draft GitHub release notes have been updated.
- [ ] CI is green (no forced merge required).
- [ ] Merge PR

### CODE REVIEW

**Comment by UziTech** [comment]
I'm not sure we want to support this way of installing marked. There are probably millions of different tools that could be used to install marked but we don't have time to make sure they all continue to work.

@styfle what do you think?

**Comment by UziTech** [comment]
it looks like the code that controls which version of marked is installed this not controlled by us anyway.

https://github.com/Homebrew/homebrew-core/blob/master/Formula/marked.rb

**Comment by styfle** [comment]
I wouldn't list it here since no one from the core team is maintaining it.

**Comment by SeekingMeaning** [comment]
Sure, no problem, we'll try to keep the package updated from our side

**Pull request closed without merging**
