### PR TITLE
Lazy load images

### PR DESCRIPTION
**Pull request by fredden**
**Marked version:** n/a
**Markdown flavor:** n/a

## Description
This pull request will add loading="lazy" to image tags. This means that the user agent can choose to delay downloading an image if it determines that will produce a better user experience.

Resources:
- https://developer.mozilla.org/en-US/docs/Web/Performance/Lazy_loading
- https://developer.mozilla.org/en-US/docs/Web/HTML/Element/img#attr-loading

## Contributor
- [x] Test(s) exist to ensure functionality and minimise regression (if no tests added, list tests covering this PR):
  - test/specs/commonmark/commonmark.0.29.json
  - test/specs/gfm/commonmark.0.29.json
  - test/specs/new/image_links.html
  - test/specs/new/image_paren.html
  - test/specs/new/main.html
  - test/specs/new/relative_base_urls.html
  - test/specs/new/relative_urls.html
  - test/specs/security/sanitizer_bypass.html
  - test/specs/security/sanitizer_bypass_remove_generic.html
  - test/unit/Parser-spec.js
- [ ] ~no tests required for this PR.~
- [ ] ~If submitting new feature, it has been documented in the appropriate places.~

## Committer
In most cases, this should be a different person than the contributor.
- [ ] Draft GitHub release notes have been updated.
- [ ] CI is green (no forced merge required).
- [ ] Merge PR

### CODE REVIEW

**Comment by UziTech** [comment]
Marked tries to follow the [CommonMark spec](https://spec.commonmark.org/0.29/) if you want the spec to change you will need to create an issue or pull request on their [repo](https://github.com/commonmark/commonmark-spec).

**Comment by UziTech** [comment]
The other way to achieve this would be to create a new [renderer](https://marked.js.org/using_pro#renderer):

```js
const renderer = {
  image(href, title, text) {
    if (href === null) {
      return text;
    }

    let out = '<img src="' + href + '" alt="' + text + '" loading="lazy"';
    if (title) {
      out += ' title="' + title + '"';
    }
    out += this.options.xhtml ? '/>' : '>';
    return out;
  }
};

marked.use({renderer});

console.log(marked('![test](img)'));
```

**Comment by UziTech** [comment]
I'm going to close this since it moves marked away from the spec and there is a way to extend marked to accomplish this.

**Comment by fredden** [comment]
Thanks Tony. Sorry for the noise. :)

**Pull request closed without merging**
