### PR TITLE
Pretty print ENOENT errors on cli

### LINKED ISSUE #205: Bad CLI error output when outputting to nonexistent directory
To repeat the problem

```
echo "hello" > test.md
cat test.md
marked test.md -o test.html
cat test.html
marked test.md -o nonexistent_dir/test.html
```

results in an error which makes you doubt the quality of marked

```
/usr/local/share/npm/lib/node_modules/marked/bin/marked:182
    if (err) throw err;
                   ^
Error: ENOENT, open 'nonexistent_dir/test.html'
```

compare it to `mv test.md nonexistent_dir/test.md` which results in: 

```
mv: rename test.md to nonexistent_dir/test.md: No such file or directory
```

### PR DESCRIPTION
**Pull request by mccraveiro**
**Marked version:** master branch

**Markdown flavor:** n/a

## Description

Hide the JS stack trace on CLI errors 

- Fixes #205 

## Contributor

- [ ] Test(s) exist to ensure functionality and minimize regression (if no tests added, list tests covering this PR); or,
- [x] no tests required for this PR.
- [ ] If submitting new feature, it has been documented in the appropriate places.

## Committer

In most cases, this should be a different person than the contributor.

- [x] Draft GitHub release notes have been updated.
- [x] CI is green (no forced merge required).
- [x] Merge PR

### CODE REVIEW

**Comment by UziTech** [comment]
I'm not sure if this is the correct solution. It would be easier to debug with the stack trace. 

If we want to fix #205 we should catch that error and show a relevant message.

**Comment by mccraveiro** [comment]
@UziTech What message would you show on #205 situation? 

I'm not sure that debugging is something one would do while using the cli. 
Should we use `NODE_ENV` to show the stack when in development mode?

**Comment by UziTech** [comment]
could be something like

```sh
marked: output to nonexistent_dir/test.html: No such directory
```

The way this PR is right now the output would be

```sh
Error: ENOENT, open 'nonexistent_dir/test.html'
```

which is not much more helpful.

**Comment by mccraveiro** [comment]
@UziTech done :)

**Pull request merged**
