### PR TITLE
fix: spaces on a newline after a table

### LINKED ISSUE #2249: Error thrown if there's a space on a newline after a table
**3.0.7:**

**Describe the bug**
An error occurs if there is a space on the newline after a table at the end of a markdown string.

**To Reproduce**

1. [Marked Demo](https://marked.js.org/demo/?text=%7C%20y%20%7C%0A%7C%20-%20%7C%0A%7C%20x%20%7C%0A%20&options=%7B%0A%20%22baseUrl%22%3A%20null%2C%0A%20%22breaks%22%3A%20false%2C%0A%20%22extensions%22%3A%20null%2C%0A%20%22gfm%22%3A%20true%2C%0A%20%22headerIds%22%3A%20true%2C%0A%20%22headerPrefix%22%3A%20%22%22%2C%0A%20%22highlight%22%3A%20null%2C%0A%20%22langPrefix%22%3A%20%22language-%22%2C%0A%20%22mangle%22%3A%20true%2C%0A%20%22pedantic%22%3A%20false%2C%0A%20%22sanitize%22%3A%20false%2C%0A%20%22sanitizer%22%3A%20null%2C%0A%20%22silent%22%3A%20false%2C%0A%20%22smartLists%22%3A%20false%2C%0A%20%22smartypants%22%3A%20false%2C%0A%20%22tokenizer%22%3A%20null%2C%0A%20%22walkTokens%22%3A%20null%2C%0A%20%22xhtml%22%3A%20false%0A%7D&version=3.0.7)
2. [CommonMark Demo](https://spec.commonmark.org/dingus/?text=%7C%20y%20%7C%0A%7C%20-%20%7C%0A%7C%20x%20%7C%0A%20)

### PR DESCRIPTION
**Pull request by imchell**
**Marked version:** 4.0.7

**Markdown flavor:** Markdown.pl|CommonMark|GitHub Flavored Markdown|n/a

## Description

- Fixes #2249
  The problem can be solved by removing the last table row with no data. The row matching `/^ {1,4}$/` should be removed. There is no need to deal with `/^ {5,}$/` since more than 4 spaces would be parsed to a fenced code block.

## Contributor

- [x] Test(s) exist to ensure functionality and minimize regression (if no tests added, list tests covering this PR); or,
- [ ] no tests required for this PR.
- [ ] If submitting new feature, it has been documented in the appropriate places.

## Committer

In most cases, this should be a different person than the contributor.

- [ ] CI is green (no forced merge required).
- [ ] Squash and Merge PR following [conventional commit guidelines](https://www.conventionalcommits.org/).

### CODE REVIEW

**Comment by UziTech** [comment]
does this fix https://github.com/markedjs/marked/issues/2278 as well?

**Comment by imchell** [comment]
> 

No, it is for #2249 solely. #2278 is getting `TypeError` exception for a similar reason, but the parse result is not the same as commonmark.js even the exception is fixed. I will look into that.

**Comment by imchell** [comment]
There are no exceptions both for #2249 and #2278 now, but the parsing result of #2278 may differ from commonmark.js because of the ambiguity between gfm table and setext heading ( #1499 ).

**Comment by UziTech** [comment]
after a little bit of experimenting it looks like a better fix would be to change the line:

```diff
-        rows: cap[3] ? cap[3].replace(/\n$/, '').split('\n') : []
+        rows: cap[3] ? cap[3].replace(/\n[ \t]*$/, '').split('\n') : []
```

basically removing any trailing space characters before creating rows.

**Comment by imchell** [comment]
Thanks. It's a better solution.

**Comment by UziTech** [comment]
@imchell can you make that change and leave the test to make sure it works?

**Comment by imchell** [comment]
@UziTech updated 👀

**Review by UziTech — APPROVED** [review]
Thanks! :100:

**Review by calculuschild — APPROVED** [review]

**Pull request merged**
