### PR TITLE
modify the list regex to solve an issue with list rendering #1461

### PR DESCRIPTION
**Pull request by ansuz**
This commit makes many tests fail, but fixes my issue. I don't know enough to tell whether that means my _"fix"_ is really wrong, or if the tests are simply specifying incorrect behaviour for the purpose of consistency.

Please advise.

### CODE REVIEW

**Comment by UziTech** [comment]
This is the wrong fix. It breaks commonmark examples like [spec#285](https://spec.commonmark.org/0.29/#example-285)

**Comment by ansuz** [comment]
I haven't found a fix, but I made a test that reproduces the issue.

If you agree that the test is correct then I can see about trying to fix the issue without breaking everything else.

**Comment by UziTech** [comment]
A list with a single blank space is considered a "loose" list ([spec example](https://spec.commonmark.org/0.29/#example-284))

the resulting html [according to commonmark](https://spec.commonmark.org/dingus/?text=*%20pew%0A*%20pew%0A*%20pew%0A%0A*%20pew%0A*%20pew) should be a single list with each element as a paragraph.

```html
<ul>
  <li>
    <p>pew</p>
  </li>
  <li>
    <p>pew</p>
  </li>
  <li>
    <p>pew</p>
  </li>
  <li>
    <p>pew</p>
  </li>
  <li>
    <p>pew</p>
  </li>
</ul>
```

**Comment by ansuz** [comment]
Is that in the original markdown spec, or is it undefined behaviour anywhere other than commonmark?

**Comment by UziTech** [comment]
according to [the original markdown spec](https://daringfireball.net/projects/markdown/syntax#list): 

> If list items are separated by blank lines, Markdown will wrap the items in `<p>` tags in the HTML output.

**Comment by UziTech** [comment]
That is the correct test. Now to find a solution that doesn't break other tests.

**Comment by UziTech** [comment]
This PR should be rebased and code changed in the `/src/` folder. Feel free to reopen this if you are still working on it.

**Pull request closed without merging**
