### PR TITLE
Federico to committer

### PR DESCRIPTION
**Pull request by joshbruce**
**@mention the contributor:** @Feder1co5oave 

## Recommendation to:

- [x] Change user group
- [x] Add a badge
- [ ] Remove a badge

#1135 - 'nut said in my book...though we could also look at just about every one of the consolidation issues as well. (Having said that, totally understand not wanting to commit to that level again yet.)

## As the one mentioned, I would like to:

- [ ] accept the recommendation; or,
- [x] gracefully decline; or,
- [ ] dispute the recommendation

within 30 days (silence is consent at this point, can't have the pull requests page filled with PRs related to badges forever).

Note: All committers must approve via review before merging, the disapproving committer can simply close the PR.

### CODE REVIEW

**Comment by Feder1co5oave** [comment]
I don't get it: what's this about?

Il mer 21 mar 2018, 22:00 Jamie Davis <notifications@github.com> ha scritto:

**Comment by joshbruce** [comment]
@Feder1co5oave: We started using the AUTHORS page to classify users and grant certain privileges. This one is an invitation to you to become a committer again based on your past and present contributions.

You can accept the invitation, decline the invitation, or dispute it for some reason. If you accept, you would be granted the ability to merge PRs and whatnot (what you had before).

**Comment by joshbruce** [comment]
See also #1148

**Comment by styfle** [comment]
@Feder1co5oave I added you to slack just so that you can keep in communication with the team ✉️ 

I'm not sure what connection you want to have this project because you stepped down in #1093 but then contributed this massive PR in #1135 🦁 

Do you want to be the dev on the sidelines or be a core member? 😄

**Comment by Feder1co5oave** [comment]
Guys, sorry for the late reply, I have a deadline coming up.
I kindly decline the offer, I cannot follow the development of marked anymore. This is due to to a mixture of rational and personal reasons. What I wrote in #1093 holds true, but that is only half (or even less) of the story.
I submitted #1135 because that was a massive WIP that kept haunting me and I had to get it out, because I hate wasting my work, but I cannot contribute anything more.
No hard feelings whatsoever on my part, I just need to go my way to focus on more important things at this moment in my life.

Have a good one y'all 🥂

**Comment by joshbruce** [comment]
No worries @Feder1co5oave. Good luck with all you do! It's been an absolute pleasure.

**Pull request closed without merging**
