### PR TITLE
Create separate CJS and UMD builds

### PR DESCRIPTION
**Pull request by benmccann**
**Marked version:** 4.0.1

**Markdown flavor:** n/a

## Description

Fixes https://github.com/markedjs/marked/issues/2265

This comment pointed out that it would be very weird to use a CJS file in the browser: https://github.com/markedjs/marked/issues/2265#issuecomment-966732495

That's true, but it's not actually CJS. It's UMD. And I think UMD was specified for the CDNs, which makes a lot more sense. It's just really confusing the way we have it setup now because the file extension doesn't match the actual file type.

Putting a UMD file as `main` is breaking people in 4.0.1. I didn't realize we were doing that in the last PR because I was thrown off by the file extensions. Bundlers generally know how to deal with CJS and ESM, but not UMD. It's reported that this change fixes things: https://github.com/markedjs/marked/issues/2265#issuecomment-967311475

## Contributor

- [ ] Test(s) exist to ensure functionality and minimize regression (if no tests added, list tests covering this PR); or,
- [X] no tests required for this PR.
- [ ] If submitting new feature, it has been documented in the appropriate places.

## Committer

In most cases, this should be a different person than the contributor.

- [ ] CI is green (no forced merge required).
- [ ] Squash and Merge PR following [conventional commit guidelines](https://www.conventionalcommits.org/).

### CODE REVIEW

**Review by UziTech — APPROVED** [review]

**Comment by UziTech** [comment]
@benmccann You have been helping out a lot recently. Would you like to join @markedjs and help maintain marked?

**Comment by benmccann** [comment]
Thanks for the offer, but I'll probably disappear once this conversion to ESM has settled down :smile:  I've got a fair amount of open source projects on my plate already

**Review by styfle — APPROVED** [review]
Its an unfortunate state of the JS ecosystem but this change looks correct, thanks!

**Comment by splch** [comment]
Just to understand this correctly, if we're using marked on the client side, we now will be using `lib/marked.umd.js`?

**Comment by UziTech** [comment]
@splch if you are using marked in a script tag you should use `/marked.min.js`. if you use marked in node or webpack you should use `import { marked } from 'marked';` and the loader should choose the correct file.

**Pull request merged**
