### PR TITLE
Converting tabs to appropriate number of spaces for proper alignment.

### LINKED ISSUE #1559: Markdown containing tabs not converted properly to spaces
**Describe the bug**
The package converts the tabs in the markdown to 4 spaces every time. It breaks the alignment of the text. It's not how tabs work. The tab indentation of the current tab in a string will be 
`tabsize - ((number of characters occupied in current tab buffer) % tabsize)`

image

**To Reproduce**
Steps to reproduce the behaviour:

1. Type any text using tabs.
2. Paste it in [Marked Demo](https://marked.js.org/demo/) for viewing parsed HTML. You will see changes in the alignment.

Below is the text that contains tabs that I am parsing to HTML.
```markdown
# markdown alignment

```
        [FirstName]				=> TEST
        [LastName]				=> TESTIN
        [EmailAddress]			=> TEST
        [CompanyName]			=> Test Company
        [Phone]					=> TEST
```
```

Demo links:
1. [Marked Demo](https://marked.js.org/demo/?text=%23%20markdown%20alignment%0A%0A%60%60%60%0A%20%20%20%20%20%20%20%20%5BFirstName%5D%09%09%09%09%3D%3E%20TEST%0A%20%20%20%20%20%20%20%20%5BLastName%5D%09%09%09%09%3D%3E%20TESTIN%0A%20%20%20%20%20%20%20%20%5BEmailAddress%5D%09%09%09%3D%3E%20TEST%0A%20%20%20%20%20%20%20%20%5BCompanyName%5D%09%09%09%3D%3E%20Test%20Company%0A%20%20%20%20%20%20%20%20%5BPhone%5D%09%09%09%09%09%3D%3E%20TEST%0A%60%60%60&options=%7B%0A%20%22baseUrl%22%3A%20null%2C%0A%20%22breaks%22%3A%20false%2C%0A%20%22gfm%22%3A%20true%2C%0A%20%22headerIds%22%3A%20true%2C%0A%20%22headerPrefix%22%3A%20%22%22%2C%0A%20%22highlight%22%3A%20null%2C%0A%20%22langPrefix%22%3A%20%22language-%22%2C%0A%20%22mangle%22%3A%20true%2C%0A%20%22pedantic%22%3A%20false%2C%0A%20%22sanitize%22%3A%20false%2C%0A%20%22sanitizer%22%3A%20null%2C%0A%20%22silent%22%3A%20false%2C%0A%20%22smartLists%22%3A%20false%2C%0A%20%22smartypants%22%3A%20false%2C%0A%20%22xhtml%22%3A%20false%0A%7D&version=master)
2. [CommonMark Demo](https://spec.commonmark.org/dingus/?text=%23%20markdown%20alignment%0A%0A%60%60%60%0A%20%20%20%20%20%20%20%20%5BFirstName%5D%09%09%09%09%3D%3E%20TEST%0A%20%20%20%20%20%20%20%20%5BLastName%5D%09%09%09%09%3D%3E%20TESTIN%0A%20%20%20%20%20%20%20%20%5BEmailAddress%5D%09%09%09%3D%3E%20TEST%0A%20%20%20%20%20%20%20%20%5BCompanyName%5D%09%09%09%3D%3E%20Test%20Company%0A%20%20%20%20%20%20%20%20%5BPhone%5D%09%09%09%09%09%3D%3E%20TEST%0A%60%60%60)

The CommonMark was also not able to parse the tabs to appropriate number od spaces.

The [ParseDown](https://packagist.org/packages/erusev/parsedown) PHP package was able to parse the tabs in text to appropriate number of spaces. Its how any user will expect the HTML output to look like. You can paste the above given markdown text in [ParseDown Demo](https://parsedown.org/demo)
image

**Expected behavior**
When I am writing a markdown containing tabs, I will expect it to give the same alignment when converted to HTML. It how any user will expect.

I am using this text:
image

The arrows aren't aligned upon parsing. It gets  parsed to HTML like this:
image
image

While, any user will expect it to be like this:
image

### PR DESCRIPTION
**Pull request by smartankur4u**
**Marked version: 0.7.0**

**Markdown flavor:** Markdown.pl|CommonMark|GitHub Flavored Markdown|n/a

## Description

- Fixes #1559

## Expectation
I expect the output to be the same what it was looking while I wrote the text.
The output is different when the text contains tabs.
I expect such output:
image

## Result
This is the output I am getting:
image

## What was attempted
I have included my package [tab-to-space](https://www.npmjs.com/package/tab-to-space) to convert tabs to the appropriate number of spaces in the Lexer prototype. This solves the alignment issue.

## Contributor

- [x] Test(s) exist to ensure functionality and minimize regression (if no tests added, list tests covering this PR); or,
- [ ] no tests required for this PR.
- [ ] If submitting new feature, it has been documented in the appropriate places.

## Committer

In most cases, this should be a different person than the contributor.

- [ ] Draft GitHub release notes have been updated.
- [ ] CI is green (no forced merge required).
- [ ] Merge PR

### CODE REVIEW

**Comment by smartankur4u** [comment]
@UziTech, @styfle 
Seems like the CI tests are failing because the node_modules are cached.

**Comment by UziTech** [comment]
looks like the tests are failing because `package-lock.json` is not in sync with `package.json`. If you run `npm i` it should fix the error.

One of the benefits of marked is that there are no dependencies. So I don't think we should add one for this.

If we are changing the behavior of tabs we also need to make sure that it complies with the CommonMark spec. https://spec.commonmark.org/0.29/#tabs

**Comment by smartankur4u** [comment]
@UziTech at present, CommonMark is also not converting tabs to the appropriate number of spaces. Does it mean we have to leave this issue as it is?
CommonMark demo: [Link](https://spec.commonmark.org/dingus/?text=%23%20markdown%20alignment%0A%0A%60%60%60%0A%20%20%20%20%20%20%20%20%5BFirstName%5D%09%09%09%09%3D%3E%20TEST%0A%20%20%20%20%20%20%20%20%5BLastName%5D%09%09%09%09%3D%3E%20TESTIN%0A%20%20%20%20%20%20%20%20%5BEmailAddress%5D%09%09%09%3D%3E%20TEST%0A%20%20%20%20%20%20%20%20%5BCompanyName%5D%09%09%09%3D%3E%20Test%20Company%0A%20%20%20%20%20%20%20%20%5BPhone%5D%09%09%09%09%09%3D%3E%20TEST%0A%60%60%60)

I recently found this issue in marked, and we had to write custom code in all the repositories where we are parsing markdown using marked NPM package.

**Comment by UziTech** [comment]
If you are looking to change the common mark spec then their [forum](https://talk.commonmark.org/) is the correct place to discuss that.

**Pull request closed without merging**
