### PR TITLE
Add module field to package.json

### PR DESCRIPTION
**Pull request by benmccann**
**Marked version:** `master`

**Markdown flavor:** n/a

## Description

- Fixes https://github.com/markedjs/marked/issues/2021

Allows `marked` to be used with SvelteKit / Vite without the currently required workaround (https://github.com/markedjs/marked/issues/2021#issuecomment-885912209)

## Contributor

- [ ] Test(s) exist to ensure functionality and minimize regression (if no tests added, list tests covering this PR); or,
- [X] no tests required for this PR.
- [ ] If submitting new feature, it has been documented in the appropriate places.

## Committer

In most cases, this should be a different person than the contributor.

- [ ] CI is green (no forced merge required).
- [ ] Squash and Merge PR following [conventional commit guidelines](https://www.conventionalcommits.org/).

### CODE REVIEW

**Comment by UziTech** [comment]
It looks like the module field was remove previously because of an issue with webpack. see https://github.com/markedjs/marked/pull/1571#issuecomment-562891963

**Comment by benmccann** [comment]
Yeah, default exports should be avoided because they're not compatible between CJS and ESM. Luckily there are named exports available, so people don't have to use the default export if they run into that. And since this is going into a major version it's a good time to do breaking changes

**Comment by UziTech** [comment]
using a named export is something I would like to change to in the future along with having marked create instances instead of being one global object. Maybe that will be a v4 fix.

**Comment by benmccann** [comment]
This PR shouldn't be an issue in the meantime. It may mean that different users have to import `marked` slightly differently if they want to use the default export depending on whether they're building for the browser or server, but at least they can import directly from `marked` instead of `./lib/marked.esm.js` if they want to use ESM

**Comment by UziTech** [comment]
This PR is an issue for anyone using webpack according to https://github.com/markedjs/marked/pull/1571#issuecomment-562891963

**Comment by benmccann** [comment]
There's a big difference in this PR vs the last time `module` was attempted to be added, which is that `package.json` now contains a `browser` field. Webpack, by default, will find the `browser` field first, which is the same as `main` and so shouldn't cause any issues for people using Webpack as a result.

Even if someone asked Webpack to use the `module` field for `marked`, it wouldn't stop people from using Webpack. It just wouldn't be backwards compatible with using the `main` field. But that shouldn't matter since the `browser` field will be chosen

The other solution to this would be to use the `exports` field in `package.json`

**Comment by UziTech** [comment]
> Webpack, by default, will find the `browser` field first, which is the same as `main` and so shouldn't cause any issues for people using Webpack as a result.

OK i'm convinced.

> The other solution to this would be to use the `exports` field in `package.json`

There actually is a PR to add the `exports` field #1725 that looks abandoned. If you wanted to create a PR for that we could get that in as well.

**Review by UziTech — APPROVED** [review]

**Comment by benmccann** [comment]
> There actually is a PR to add the exports field #1725 that looks abandoned. If you wanted to create a PR for that we could get that in as well.

That PR generally looks good to me. I just left some comments on it. It was adding build output in `lib/marked.esm.mjs` and I wasn't sure if it should be?

**Review by styfle — APPROVED** [review]
I'm not a huge fan of `module` since its not standardized, but it seems more tools are relying on it so we can try it out with 3.0 since its semver major

**Pull request merged**
