### PR TITLE
Update release template

### PR DESCRIPTION
**Pull request by joshbruce**
**Marked version:** 0.3.17

## Description

See [comment](https://github.com/markedjs/marked/issues/1097#issuecomment-369282046) from @intcreator for context.

> Perhaps we can make clear which version of the spec each version of Marked adheres to so if people want compatibility available in a certain version of the spec they can use the corresponding version of Marked? Potentially even syncing Marked versioning to the spec in some way?

## Contributor

- [ ] Test(s) exist to ensure functionality and minimize regresstion (if no tests added, list tests covering this PR); or,
- [x] no tests required for this PR.
- [ ] If submitting new feature, it has been documented in the appropriate places.
  
## Committer

In most cases, this should be a different person than the contributor.

- [ ] Draft GitHub release notes have been updated.
- [ ] cm_autolinks is the only failing test (remove once CI is in place and all tests pass).
- [ ] All lint checks pass (remove once CI is in place).
- [ ] CI is green (no forced merge required).
- [ ] Merge PR

### CODE REVIEW

**Comment by intcreator** [comment]
Looks good!

**Comment by joshbruce** [comment]
This is interesting. Who should merge?

1. First reviewer once all identified reviewers have approved?
2. Last identified reviewer?
3. Or the submitter?

Basically, who's responsible for running the committer checklist?

In Release Planning for the day job; so, might slow down a bit.

**Comment by intcreator** [comment]
> ## Committer
>
> In most cases, this should be a different person than the contributor.

I think any of the reviewers are fair game.  If everyone approves the PR, then I don't think who runs through the checklist matters that much as long as it's a fresh set of eyes.

**Comment by joshbruce** [comment]
@intcreator: Lunch break for the day job! 

Fair point. 

I suppose I'm leaning (you'll see what I did there in a moment) toward identifying the [Directly Responsible Individual](https://medium.com/@mmamet/directly-responsible-individuals-f5009f465da4) for the task of merging a PR that is unambiguous. (First time I ever heard this term was while learning about all things [Lean](https://en.wikipedia.org/wiki/Lean_manufacturing).

Historically, this project has operated under something of a benevolent dictator for life model. Think they started moving toward a more liberal and consensus-driven model. Think we might be ready to go toward a third model, but it seems we're still on the consensus-driven model a bit.

So, once consensus is met among identified reviewers, which committer owns the task of merging the PR? 

In this case:

1. @styfle,
2. @UziTech, or
3. me.

Seems we're all in agreement that it shouldn't necessarily be me.

 One of the other issues we've had in the past, is that PRs don't really get merged because people were being _extra_ considerate might be a good way of describing it. To your point, the checklist is as important; however, having at least one person identified as "approving" this message (should be two, but there may be a point where marked can actually be maintained by one person).

**Pull request merged**
