### PR TITLE
Fix breaks

### LINKED ISSUE #1505: 0.6.1 -> 0.6.2 broke `breaks` option (Regression)
**Describe the bug**
After updating from `0.6.1` to `0.6.2`, I noticed that my linebreaks got lost.

**To Reproduce**
`0.6.1` with option `breaks` enabled:
```
A
B
```
output:
```
<p>A<br>B</p>
```
(which is correct)

with `0.6.2` it becomes:
```
<p>A
B</p>
```

### PR DESCRIPTION
**Pull request by UziTech**
**Marked version:** 0.6.2

**Markdown flavor:** GitHub Flavored Markdown with breaks

## Description

the `breaks: true` option broke in v0.6.2 because of #1460 

This reverts the change only when the `breaks` option is set to true.

- Fixes #1505 

## Contributor

- [x] Test(s) exist to ensure functionality and minimize regression

## Committer

In most cases, this should be a different person than the contributor.

- [ ] Draft GitHub release notes have been updated.
- [ ] CI is green (no forced merge required).
- [ ] Merge PR

### CODE REVIEW

**Comment by UziTech** [comment]
This fixes the breaks but it adds back the redos in [quadradic_br.js](https://github.com/markedjs/marked/pull/1460/files#diff-f1f1b91e274a613c8041d4c39925bb12) when `breaks: true` option is used.

**Comment by UziTech** [comment]
This should probably be released soon since this probably affects a lot of marked users

**Comment by davisjam** [comment]
Let's get this merged. I think fixing a behavior regression is more important than a performance regression.

**Comment by fdietze** [comment]
Thank you!

**Pull request merged**
