### PR TITLE
Adding Tools using Marked in docs

### LINKED ISSUE #2337: Readme: List of tools for simple-page creation.
**What pain point are you perceiving?.**
I want a comprehensive list of tools that build on Markedjs for creating webpages.

I have found the following:

http://strapdownjs.com/
https://zerodevx.github.io/zero-md/

**Describe the solution you'd like**
If anyone knows of other tools like strapdownjs, or zero-md, please add a comment.

Maybe such tools should be added to the Readme?

### PR DESCRIPTION
**Pull request by mstomar698**
Adds new section for Tools using Marked

**Marked version:**

**Markdown flavor:** Markdown.pl|CommonMark|GitHub Flavored Markdown|n/a

## Description

- Fixes #2337

## What was attempted

Adding Tools table in docs,
- These tools are single-page creation tools using Marked.

## Result
image

Added this.

## Contributor

- [x] no tests are required for this PR.

### CODE REVIEW

**Comment by 201B153** [comment]
Sorry!! it was conflicting that's why I have to make another PR for the same issue.

**Comment by 201B153** [comment]
Should I add this issue #2598 to the PR too?

**Comment by UziTech** [comment]
I think instead of the status column we should have a description column. If the status of one of them ever becomes "Inactive" I don't think it would get updated for a while.

**Comment by 201B153** [comment]
ok i will update it.

**Comment by 201B153** [comment]
It looks like this now.
image

**Comment by 201B153** [comment]
@UziTech  can u review it now?

**Review by UziTech — APPROVED** [review]
LGTM

**Review by calculuschild — APPROVED** [review]

**Comment by mstomar698** [comment]
sorry abt closing the PR.
I'm totally new to open source.
Sorry

**Comment by calculuschild** [comment]
@mstomar698 It seems like you might be having trouble with this PR as you keep making new ones. Is there some way we can help streamline the process for you?

**Comment by mstomar698** [comment]
Sorry about that.
I get a branch conflict due to a name change so Sorry. 
This would be the last one please review it.
I made all possible changes in the new PR.

**Pull request closed without merging**
