### PR TITLE
fix: Replace custom `repeatString` function with `repeat()`

### PR DESCRIPTION
**Pull request by DreierF**
**Marked version:**

5.0.3

## Description

While working on #2805 I noticed that there are a few `repeatString` functions that could trivially be replaced with [`String.proptotype.repeat()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/repeat), which is already used in some other places in the code anyway.

## Contributor

- [x] Test(s) exist to ensure functionality and minimize regression (if no tests added, list tests covering this PR); or,
  - New em_list_links
  - New em_and_reflinks
  - CommonMark Emphasis and strong emphasis
  - CommonMark Links
  - CommonMark HTML blocks
  - Original markdown_documentation_basics
  - Original markdown_documentation_syntax
  - GFM HTML blocks
  - GFM Emphasis and strong emphasis
  - GFM Links
- [ ] no tests required for this PR.
- [ ] If submitting new feature, it has been documented in the appropriate places.

## Committer

In most cases, this should be a different person than the contributor.

- [ ] CI is green (no forced merge required).
- [ ] Squash and Merge PR following [conventional commit guidelines](https://www.conventionalcommits.org/).

### CODE REVIEW

**Review by UziTech — APPROVED** [review]
Thanks for doing this!

**Review by joshbruce — APPROVED** [review]

**Review by styfle — APPROVED** [review]
Great, thanks!

**Comment by davisjam** [comment]
Should be same-or-faster unless we're repeating really small strings, in which case the implementation shouldn't matter anyway. But it's nice to use the built-in language feature.

Do all marked-supported language runtimes now support `repeat`?

**Comment by styfle** [comment]
We don't have a list of supported runtimes outside of Node.js as far I know.

We support Node.js 18 and newer since Marked 5.0.0 (see https://github.com/markedjs/marked/pull/2767)

**Pull request merged**
