### PR TITLE
Introducing Prettier: Simplifying Code Formatting and Enhancing Consistency

### PR DESCRIPTION
**Pull request by wallpants**
Dear marked Team,

I hope this message finds you well. I am writing to propose the addition of [Prettier](https://prettier.io/), a code formatter, to marked's codebase. This tool is designed to streamline the code formatting process and reduce the need for manual adjustments, enhancing code consistency across the project. I was motivated to create this PR after trying to add some features and finding a bunch of format inconsistencies across the codebase.

I'm not saying that the prettier/eslint config included in this PR is necessarily the one to keep, but it's a starting point. I personally have no preference as to what the code should look like, as long as it works and it's consistent across the entire codebase.

Eslint rules were updated for easier integration with Prettier.

Here are some compelling reasons to consider this addition:

### Consistency and Readability
Prettier enforces a consistent code style across the project, making it easier for developers to read and understand each other's code. This ensures that the codebase maintains a high level of readability and accessibility.

### Reduced Nit-Picking and Code Reviews
With Prettier, the code formatting is defined in a configuration file, significantly reducing the likelihood of nit-pick change requests related to code style. This allows us to focus more on the substantive aspects of the code during code reviews.

### Savings in Time and Effort
Developers can avoid spending time manually formatting code. Instead, they can rely on Prettier to handle these tasks, allowing them to focus on writing and improving functionality.

### Configuration Flexibility
Prettier's configuration file allows us to adapt the formatting rules to suit our specific preferences and requirements. This means there's full control over how the codebase is formatted.

## Maintaining Test Integrity
I have ensured that the formatting changes only apply to the main codebase, excluding the tests directory intentionally. This means that tests will run exactly as they did before, eliminating any concerns about formatting changes affecting test results. Once this PR gets approved and merged, test files can also be formatted with this tool.

I have submitted this as a Pull Request, and I invite you to review the changes made by Prettier. I'm confident that this addition will enhance the development process and lead to more consistent, maintainable code.

Thank you for considering this proposal. I look forward to hearing your thoughts and feedback.

Whoever reviews this PR, if it ever is reviewed, I'd suggest you review it by commits rather than by files changed.

Warm regards,
wallpants

### CODE REVIEW

**Comment by UziTech** [comment]
We already have eslint that does all of the things you mentioned as benefits. So what is the benefit of using prettier for formatting and eslint for linting over just using eslint for both?

**Comment by wallpants** [comment]
There are a lot of changes that can be made to the codebase style-wise with the current configuration (without prettier) that eslint will allow and wont fix. It would seem like you believe otherwise, or y'all are okay with the inconsistencies this allows.

There are less rules to maintain in the eslint config files. You could argue that there's now a need to maintain the prettier config file, but it can very easily be removed and defaults can be used.

Prettier is more opinionated and will cover **_every single line of code_** and make them consistent, making the codebase feel more cohesive and as if it had been written by one person, making it easier to read for anyone involved.

**Comment by UziTech** [comment]
Ya I don't mind the inconsistencies in our code base any more than the inconsistencies in a code base with prettier.

I don't know if that is worth 3 extra dependencies.

**Comment by wallpants** [comment]
I'm not really sure what you mean by inconsistencies in a codebase with prettier. Inconsistencies is what prettier aims to remove.

I'm honestly a bit surprised that dev dependencies that offer dx improvements are something we're worried about. I removed the pre-commit hook dependency `husky`, the plugin to sort imports, and unnecessary eslint packages. If this were to be approved `marked` would be at `-2` dev dependencies from what y'all currently have. I imagine you'll find this very exciting.

new dependency:
1. prettier

removed dependencies:
1. eslint-config-standard
2. eslint-plugin-n
3. eslint-plugin-promise

I'm curious about how y'all handle formatting with eslint. I can't seem to find anything in the codebase that will automatically run `eslint --fix .` . Do y'all just wait until the github workflow fails and then manually run `npm run lint` on your local system and push again? Do you rely on the developer remembering to manually run the command before pushing? This is exactly what the pre-commit hook aimed to solve.

Anyway, thank you for taking the time to look at this PR and for building such a good library. I leave this PR on your hands. Feel free to close it or update with any changes you deem necessary.

Cheers

**Comment by UziTech** [comment]
> I'm not really sure what you mean by inconsistencies in a codebase with prettier

I don't really see any inconsistencies without prettier either. That is kind of the point.

> Do y'all just wait until the github workflow fails and then manually run npm run lint on your local system and push again?

Ya same as tests. Usually people's ide auto formats with eslint. So it is the tests that require more pushes most of the time.

> I'm honestly a bit surprised that dev dependencies that offer dx improvements are something we're worried about.

What dx improvements? Thats what I tried figuring out with my first question. You say it is easier to read, but I don't think the code in this PR is any easier to read than without prettier. I use prettier in some of the other repos I maintain but I don't really see the benefit.

**Comment by UziTech** [comment]
I'm not opposed to using it. I think the code looks fine with it but I just don't think it is worth the change

**Comment by wallpants** [comment]
Good luck

**Pull request closed without merging**
