### PR TITLE
show failing test when original tests takes > 1s

### PR DESCRIPTION
**Pull request by UziTech**
**Marked version:** 0.3.19

## Description

- Shows which tests are failing because of taking too long like in #1226 

## Contributor

- [ ] Test(s) exist to ensure functionality and minimize regression (if no tests added, list tests covering this PR); or,
- [X] no tests required for this PR.
- [ ] If submitting new feature, it has been documented in the appropriate places.

## Committer

In most cases, this should be a different person than the contributor.

- [x] Draft GitHub release notes have been updated.
- [x] CI is green (no forced merge required).
- [x] Merge PR

### CODE REVIEW

**Comment by joshbruce** [comment]
@styfle: You caught me while I was updating the notes. lol

**Comment by styfle** [comment]
@joshbruce Oops, did we lose something?

**Comment by joshbruce** [comment]
@styfle: There's a slight chance we might have lost something in the Release Notes. I consolidated some, which may have been an area you were adding them to. Double-check??

**Comment by styfle** [comment]
@joshbruce They're all there 👍

**Pull request merged**
