### PR TITLE
Some highlighters require class on a wrapping element to render properly

### PR DESCRIPTION
**Pull request by meeDamian**
This is one of the possible solutions. Any thoughts?

[Review on Reviewable](https://reviewable.io/reviews/chjj/marked/418)

### CODE REVIEW

**Comment by chester1000** [comment]
Updated my repo to the latest codebase. Still can't get why it can't be merged.

**Comment by xdumaine** [comment]
Bump. @chjj?

**Comment by stoffeastrom** [comment]
Please merge!

**Comment by Huxpro** [comment]
Please merge!

**Comment by akuma** [comment]
Please merge!

**Comment by tzi** [comment]
Please :)

**Comment by sovanna** [comment]
it could help a lot of people... instead, we use workaround ..

**Comment by wells** [comment]
@chjj Please merge this.

**Comment by ee7klt** [comment]
@chjj please merge ;)

**Comment by joshbruce** [comment]
#983

**Comment by lyswhut** [comment]
> 我将`langPrefix:'hljs '`在`marked.setOptions`解决

When the language is undefined, `langPrefix` does not work, such as:
````markdown
```
console.log('hahaha')
```
````
Will be rendered as:
```html
<pre><code><span class="hljs-built_in">console</span>.log(<span class="hljs-string">'hahaha'</span>)</code></pre>
```
The code block will be missing the 'hljs' class.
My solution is:
```js
const marked = require('marked')
const hljs = require('highlight.js')
const renderer = new marked.Renderer()
const doRenderCode = (code, lang) => lang ? hljs.highlight(lang, code, true).value : hljs.highlightAuto(code).value
renderer.code = (code, lang) => `<pre><code class="hljs ${lang || ''}">${doRenderCode(code, lang)}</code></pre>`
const markedOptions = {
   Renderer
   // langPrefix: 'hljs ',
   // highlight: (code, lang) => lang ? hljs.highlight(lang, code, true).value : hljs.highlightAuto(code).value
}
console.log(marked(markdownStr, markedOptions))
```
Input markdown string：
````markdown
```
console.log('hahaha')
```

```js
console.log('hahaha')
```
````
Will be rendered as:
```html
<pre><code class="hljs "><span class="hljs-built_in">console</span>.log(<span class="hljs-string">'hahaha'</span>)</code></pre>
<pre><code class="hljs js"><span class="hljs-built_in">console</span>.log(<span class="hljs-string">'hahaha'</span>)</code></pre>
```

**Pull request closed without merging**
