### PR TITLE
fix: update min node to v18

### PR DESCRIPTION
**Pull request by UziTech**
> # 🚨  BREAKING CHANGE 🚨 
> do not submit until we are ready to release v5.0.0

## Description

Update minimum node version to v18

## Contributor

- [x] Test(s) exist to ensure functionality and minimize regression (if no tests added, list tests covering this PR); or,
- [ ] no tests required for this PR.
- [ ] If submitting new feature, it has been documented in the appropriate places.

## Committer

In most cases, this should be a different person than the contributor.

- [ ] CI is green (no forced merge required).
- [ ] Squash and Merge PR following [conventional commit guidelines](https://www.conventionalcommits.org/).

### CODE REVIEW

**Review by styfle — COMMENTED** [review]
Lets also include 16 since its still in maintenance until September

https://github.com/nodejs/Release/blob/main/README.md

**Comment by UziTech** [comment]
Since v16 is out of active support I think it would be better to skip supporting it rather than require another major release in September. We can wait for v20 to come out before merging this.

https://nodejs.org/en/blog/announcements/nodejs16-eol

**Comment by styfle** [comment]
Are there other upcoming breaking changes we can batch this in with?

**Comment by UziTech** [comment]
Ya there is #2766. I would also like to fix #1745 adding a param to html renderer that tells it if it is block html or inline html.

**Comment by calculuschild** [comment]
Any other options we can extract into extensions?

**Comment by UziTech** [comment]
Ya there are some easy ones that can be moved to extensions without adding hooks, like `baseUrl`, `langPrefix`, and `mangle`.

`headerIds` and `headerPrefix` already have the [marked-gfm-heading-id](https://github.com/markedjs/marked-gfm-heading-id) extension.

Although with `headerId` being `true` by default it may affect a lot more users if we deprecate it.

**Comment by UziTech** [comment]
Now that node V20 is out I think we should merge these breaking changes (#2766, #2767, and #2768) and release v5.

**Review by styfle — APPROVED** [review]

**Review by calculuschild — APPROVED** [review]

**Comment by benmccann** [comment]
Is there any code in `marked` that actually requires Node 18? We use marked in our framework and while we use Node 18 in our own projects, we couldn't drop Node 16 support as it's a breaking change and we only infrequently release new majors. I'm curious if there's a pressing reason to drop Node 16 and if it might be able to be added back?

**Comment by UziTech** [comment]
The only code that I know of that requires node 18 is in our build system. Marked should work with node 12 still. This minimum node requirement just means we only test on node v18+

**Comment by UziTech** [comment]
If you see something that doesn't work it would be ok to submit a PR to make it work with node 16. We just can't guarantee it will continue to work with node 16

**Comment by benmccann** [comment]
Thanks. The `engines` field in `package.json` prevents it from being installed. Would it be okay if I send a PR to either lower the value in that field or remove that field?

**Comment by UziTech** [comment]
No because we wouldn't be able to verify every change works with node 16. I think if you still need node v16 support it would be best for you to continue using marked v4. Node 16 eol is later this year. It should be fine for you to wait to update to marked v5 and drop node v16 support to after that.

**Comment by benmccann** [comment]
Yeah, we'll probably stick with marked 4. I'm curious what in the build process requires Node 18. If it's easy enough maybe I could make it support Node 16 as well

**Comment by UziTech** [comment]
Semantic release requires node v18

**Comment by yoyo837** [comment]
The minimum version requirement of node 18 is too aggressive.

**Comment by benmccann** [comment]
I sent a PR to lower the version in the `engines` field: https://github.com/markedjs/marked/pull/2886

> Semantic release requires node v18

The release job only runs on the latest lts version of Node, so that won't block supporting older versions. We can still test `marked` against older versions regardless of what versions sematic release supports

**Pull request merged**
