### PR TITLE
Fix: TextRenerer.paragraph is not a function

### PR DESCRIPTION
**Pull request by FlorianKoerner**
## Description

The method `paragraph` is missing in the TextRenderer.

## Result

```
TypeError: this.renderer.paragraph is not a function
```

## What was attempted

```
marked('Test', {
    renderer: new marked.TextRenderer()
})
```

## Contributor

- [ ] Test(s) exist to ensure functionality and minimize regression (if no tests added, list tests covering this PR); or,
- [ ] no tests required for this PR.
- [ ] If submitting new feature, it has been documented in the appropriate places.

## Committer

In most cases, this should be a different person than the contributor.

- [ ] Draft GitHub release notes have been updated.
- [ ] CI is green (no forced merge required).
- [ ] Merge PR

### CODE REVIEW

**Comment by UziTech** [comment]
@FlorianKoerner what was the purpose of setting the TextRenderer as the Renderer in marked?

**Comment by FlorianKoerner** [comment]
Originally my intention was to parse only inline blocks. Meanwhile I know that the TextRenderer is the wrong tool for this.

Is there an easy way to render only inline blocks?

**Comment by joshbruce** [comment]
See lines 856 to 858:

```js
Renderer.prototype.paragraph = function(text) {
  return '<p>' + text + '</p>\n';
};
```

Is this what you were trying to access @FlorianKoerner and received a bad function call reference??

**Comment by joshbruce** [comment]
Not that I can tell given the way the renderer is described at the moment. Having said that, it might make sense in the future. We have inline and block flavors of the lexer and parser...and almost the renderer.

**Comment by joshbruce** [comment]
Tagging with #746 something to potentially introduce in 1.x or 2.x

**Pull request closed without merging**
