### PR TITLE
Release v1.2.0

### PR DESCRIPTION
**Pull request by UziTech**
## Release Notes

---

## Features
- Add dry run capabilities to default slugger #1728
- Parse inline #1761

## Fixes
- Fix html comments #1739 
- Fix line break #1746
- Fix indented tables to follow gfm spec #1748 
- Fix underscore adjacent to asterisk #1755

## Dependencies
- Regenerate lock file #1736

## Documentation
- Add api dingus for babelmark #1742
- Update docs to use static build step and clean URLs via Vercel #1749

---

## Publisher

- [x] `$ npm version` has been run.
- [x] Release notes in [draft GitHub release](https://github.com/markedjs/marked/releases) are up to date
- [x] Release notes include which flavors and versions of Markdown are supported by this release
- [x] Committer checklist is complete.
- [x] Merge PR.
- [x] Publish GitHub release using `master` with correct version number.
- [x] `$ npm publish` has been run.
- [x] Create draft GitHub release to prepare next release.

Note: If merges to `master` occur after submitting this PR and before running `$ npm pubish` you should be able to

1. pull from `upstream/master` (`git pull upstream master`) into the branch holding this version,
2. run `$ npm run build` to regenerate the `min` file, and
3. commit and push the updated changes.

## Committer

In most cases, this should be someone different than the publisher.

- [x] Version in `package.json` has been updated (see [PUBLISHING.md](https://github.com/markedjs/marked/blob/master/docs/PUBLISHING.md)).
- [ ] The `marked.min.js` has been updated; or,
- [x] release does not change library.
- [x] CI is green (no forced merge required).

### CODE REVIEW

**Review by styfle — APPROVED** [review]

**Review by joshbruce — APPROVED** [review]

**Comment by joshbruce** [comment]
@UziTech and @styfle: Before I push the release, want to make sure the checklist instructions are still correct - been a minute for me.

**Comment by UziTech** [comment]
Ya just need to make sure you pull the changes in master after this PR is merged, then run `npm publish`. If you want me to do it I can.

**Comment by joshbruce** [comment]
Would you please? Have to mess it up from lack of practice. (Been in PHP deployment land.)

**Comment by styfle** [comment]
We could probably remove the checkboxes for the following:

- [ ] The marked.min.js has been updated; or,
- [ ] release does not change library.

Since we have the bot, the minified file should always be up to date.

**Comment by UziTech** [comment]
What do you guys think about moving to semantic release. I think we talked about it before and decided to wait until after v1.0.

**Comment by styfle** [comment]
I haven't used it before but it sounds good to me 👍 

Would it be better to change to squash merge at the same time so we don't need to waste time with commit messages in PRs, just the merged commit message?

**Comment by UziTech** [comment]
ya or we could use [commitlint](@commitlint/config-conventional) to enforce commit messages. I tend to prefer squashing though.

**Comment by styfle** [comment]
The reason why I dislike commit lint is that it discourages outside collaboration, especially new users who don't understand `git amend` or `git rebase`.

Lets do squash merging + semantic release 🚀

**Comment by joshbruce** [comment]
Thought we already were - soon as we hit 1.0 the expectation would be minor (new feature, non-BC) and patch (bug fixes). ??

Think some of the roadmap notes are still available in the projects tab.

I'm a good example of what @styfle is talking about. I don't use Git CLI because I typically don't have a need for features beyond what I get from GitHub Desktop. I've debated about switching to Squash to reduce number of commits recorded (if I read up on it properly) but still haven't.

**Comment by styfle** [comment]
Great! I switched to squash merging for PRs going forward 👍 

@UziTech Do you want to enable semantic release since you're more familiar with it?

**Comment by UziTech** [comment]
Ya I'll create a PR shortly to use semantic release.

**Pull request merged**
