### PR TITLE
Update Lexer.js

### LINKED ISSUE #1766: Using custom Tokenizer disables url rule
**Workaround**
For those coming from Google looking for a resolution, here's a simple solution:

```javascript
const marked = require('marked')

const lexer = new marked.Lexer({
  ...marked.defaults,
  tokenizer: new marked.Tokenizer()
})

console.log(lexer.tokenizer.rules.inline.url)

```

**Describe the bug**
When creating a lexer and passing in a tokenizer (`tokenzier: new marked.Tokenizer()`), the `url` rule gets assigned a value of `{ exec: [Function: noopTest] }`.

**To Reproduce**
See this example on Repl.it: https://repl.it/@trevorhreed/marked-multi-instance#index.js

Here's the minimal example: 

```javascript
const marked = require('marked')

const lexer1 = new marked.Lexer()
console.log(lexer1.tokenizer.rules.inline.url) // Output: /^((?:ftp|https?):\/\/|www\.)(?:[a-zA-Z0-9\-]+\.?)+[^\s<]*|^[A-Za-z0-9._+-]+(@)[a-zA-Z0-9-_]+(?:\.[a-zA-Z0-9-_]*[a-zA-Z0-9])+(?![-_])/i

const lexer2 = new marked.Lexer({
  tokenizer: new marked.Tokenizer()
})
console.log(lexer2.tokenizer.rules.inline.url) // Output: { exec: [Function: noopTest] }
```

**Expected behavior**
I expect the ruleset to be the same regardless of whether or not I pass in a tokenizer that I've instantiated myself or not (assuming all other options passed into the Lexer/Tokenizer are the same).

### PR DESCRIPTION
**Pull request by trevorhreed**
**Marked version: 1.2.0**
**Markdown flavor:** n/a

## Description

- Fixes #1766

## Contributor

*This PR may break existing functionality and may not be appropriate until a bump in major version*

- [ ] Test(s) exist to ensure functionality and minimize regression (if no tests added, list tests covering this PR); or,
- [ ] no tests required for this PR.
- [ ] If submitting new feature, it has been documented in the appropriate places.

## Committer

In most cases, this should be a different person than the contributor.

- [ ] Draft GitHub release notes have been updated.
- [ ] CI is green (no forced merge required).
- [ ] Merge PR

### CODE REVIEW

**Comment by UziTech** [comment]
this makes marked about 2x slower

**Comment by trevorhreed** [comment]
How often is the constructor being called?

**Comment by UziTech** [comment]
Once per call. But the bench marks go from ~6s to ~8s with this. I was exaggerating a little when I said 2x but it is unnecessarily slower which is why we recommend setting the options before running markdown through marked.

**Comment by UziTech** [comment]
I think the fix in https://github.com/markedjs/marked/issues/1766#issuecomment-700279699 is a much better solution.

**Comment by trevorhreed** [comment]
That solution works for me.

**Pull request closed without merging**
