### PR TITLE
Release 0.3.16

### PR DESCRIPTION
**Pull request by joshbruce**
## Submitter

- [x] `$ npm version` has been run.
- [ ] Reviewer checklist is complete.
- [ ] Merge PR.
- [ ] Publish GitHub release using `master` with correct version number.
- [x] `$ npm publish` has been run.
- [ ] Create draft GitHub release to prepare next release.

## Reviewer

- [ ] Version in `package.json` has been updated (see [RELEASE.md](https://github.com/markedjs/marked/blob/master/RELEASE.md)).
- [ ] The `marked.min.js` has been updated; or,
- [ ] release does not change library.
- [ ] All tests pass (remove once CI is in place).
- [ ] All lint checks pass (remove once CI is in place).

### CODE REVIEW

**Comment by joshbruce** [comment]
Want to make sure everyone can merge and confirm that this is what should be seen almost every time we do a release. Can last one to confirm do the merge? (Unless you think I broke something.)

Once merged I'll put the GitHub release package together.

**Comment by UziTech** [comment]
I can see the big green button 👍

Should the min file have been updated in the same commit as the version?

**Comment by joshbruce** [comment]
@UziTech: Yes. That's what doing it as a `preversion` gets us...both version and minification at the same time. Are you not seeing it?

screen shot 2018-02-20 at 3 34 09 pm

**Comment by styfle** [comment]
FYI, the link to RELEASE.md in your comment above is broken:

> Version in package.json has been updated (see RELEASE.md).

**Comment by UziTech** [comment]
@joshbruce I am seeing it in it's own commit: [Run updated deployment sequence](https://github.com/markedjs/marked/pull/1067/commits/5f765201af4aa021d7adaf5c68b550325b2818db).

I thought it would be in the same commit as the version update [0.3.16](https://github.com/markedjs/marked/pull/1067/commits/635bbe078c20faee4539896f4337145a113acf9a)

**Comment by joshbruce** [comment]
Hmmm...fair. Could be the way the `preversion` hook works...??

1. We run `$ npm version`
2. NPM runs `$ npm run preversion` - creates the `min` file (does not commit)
3. NPM update `package.json` - possibly commits??
4. We commit in order to submit PR...ultimate (or final) commit??

Thoughts?

**Comment by joshbruce** [comment]
@UziTech: I definitely did not create a commit with the 0.3.16 message; that's what's helping get me there.

**Comment by UziTech** [comment]
Yup looks like npm only adds package.json and package-lock.json to the commit. I thought it would automatically add the min file too.

**Comment by UziTech** [comment]
Maybe we should add an automatic commit after the build

```js
"preversion": "npm run build && git diff --quiet || git commit -am'minify'"
```

**Comment by joshbruce** [comment]
@UziTech: Picking up on the adoption curves conversation from elsewhere (ES6), I prefer GitHub Desktop over Terminal. Never tried to do a push + PR without coming off the back-end of a commit I performed. So, not sure how explicit it will be for someone like me to know to do the PR after all things automated.

Willing to give it a shot though.

**Comment by joshbruce** [comment]
Having said that, the latest version of GitHub Desktop doesn’t let you submit PRs directly from it anymore...so...there is that.

**Comment by joshbruce** [comment]
see #1076

**Pull request closed without merging**
