### PR TITLE
fix: Replace use of startsWith and endsWith with regex for IE11

### LINKED ISSUE #1876: Use of `startsWith` and `endsWith` breaks IE11
**Marked version:** 1.2.6 (not sure when change was introduced)

**Describe the bug**
The use of `startsWith` and `endsWith` in the source breaks IE11

**To Reproduce**
1. Launch IE11
1. Open Developer Tools
1. Click on Console tab
1. Visit https://docsify.js.org (which uses marked 1.2.6)
1. Note error message

**Expected behavior**
Expected marked to continue to work in IE11 until support is officially dropped in a future major version.

### PR DESCRIPTION
**Pull request by jhildenbiddle**
**Marked version:** 1.2.6 (not sure when change was introduced)

**Markdown flavor:** n/a

## Description

- Fixes #1876

## Expectation

No errors in IE11. 

Specifically, marked 1.x is a dependency of https://docsify.js.org which still supports IE11. Goal is to restore IE11 functionality by fixing this issue within marked.

## Result

After fixes, no erros in IE11.

## What was attempted

Replaced use of `String.startsWith()` and `String.endsWith()` with regular expression tests.

## Contributor

Verified all tests succeeded
Manually verified changes worked in IE11

- [ ] Test(s) exist to ensure functionality and minimize regression (if no tests added, list tests covering this PR); or,
- [x] no tests required for this PR.
- [ ] If submitting new feature, it has been documented in the appropriate places.

## Committer

In most cases, this should be a different person than the contributor.

- [ ] CI is green (no forced merge required).
- [ ] Squash and Merge PR following [conventional commit guidelines](https://www.conventionalcommits.org/).

### CODE REVIEW

**Review by UziTech — APPROVED** [review]
LGTM. FYI we are planning on releasing v2 soonish and we will be dropping es5 support at that time.

**Comment by calculuschild** [comment]
@UziTech is there any concern with redos? Would `string[0]`, `string[string.length]` be better?

**Comment by jhildenbiddle** [comment]
@UziTech Sounds good. 

Similarly, we're just tidying up loose ends on docsify v4 (which supports IE11) before moving on to v5 (which will also drop support for IE11). There's no expectation of long-term IE support from marked. We're all ready to put those dark days behind is. 😉

**Comment by UziTech** [comment]
@calculuschild no there are no quantifiers so it can't be vulnerable but `string.charAt(string.length - 1)` is probably faster though.

**Review by styfle — APPROVED** [review]

**Pull request merged**
