### PR TITLE
fix: Remove esm interop

### PR DESCRIPTION
**Pull request by benmccann**
**Marked version:** 3.0.5

**Markdown flavor:** all

## Description

Alternative to https://github.com/markedjs/marked/pull/2224

## Contributor

- [ ] Test(s) exist to ensure functionality and minimize regression (if no tests added, list tests covering this PR); or,
- [X] no tests required for this PR.
- [ ] If submitting new feature, it has been documented in the appropriate places.

## Committer

In most cases, this should be a different person than the contributor.

- [ ] CI is green (no forced merge required).
- [ ] Squash and Merge PR following [conventional commit guidelines](https://www.conventionalcommits.org/).

### CODE REVIEW

**Comment by UziTech** [comment]
This still seems to have not fixed it.

**Comment by benmccann** [comment]
I will take a look now that I know what the issue is and see if I can come up with a better fix

**Comment by thexs-dev** [comment]
This import line is working fine 3.0.7 as suggested above, but not for 4.0
import * as marked from 'https://cdn.jsdelivr.net/npm/marked@3.0.7/lib/marked.js';

I know it's a trivial question, but I don't know the answer
How can I adapt that import line to load marked@4.0 ?
Thanks in advance

**Comment by styfle** [comment]
Try the ESM file

https://cdn.jsdelivr.net/npm/marked@4.0.3/lib/marked.esm.js

**Pull request merged**
