### PR TITLE
drop node 10 support

### PR DESCRIPTION
**Pull request by UziTech**
## Description

Drop support for node 10 in v3

## Contributor

- [ ] Test(s) exist to ensure functionality and minimize regression (if no tests added, list tests covering this PR); or,
- [x] no tests required for this PR.
- [ ] If submitting new feature, it has been documented in the appropriate places.

## Committer

In most cases, this should be a different person than the contributor.

- [ ] CI is green (no forced merge required).
- [ ] Squash and Merge PR following [conventional commit guidelines](https://www.conventionalcommits.org/).

### CODE REVIEW

**Comment by UziTech** [comment]
Node 10 is passed EOL and since we are doing a major version with #2112 and #2124 I figured we might as well drop support.

**Review by calculuschild — APPROVED** [review]

**Comment by calculuschild** [comment]
Does this open up any more modern JS syntax that we've been missing out on? Optional chaining isn't supported until Node 14 I think, right?

**Comment by UziTech** [comment]
according to https://node.green the following were added in node v12:

- String.matchAll
- Promise.allSettled
- GlobalThis
- Numeric Separators
- public and private fields

**Review by styfle — APPROVED** [review]
Nice 👍

**Pull request merged**
