### PR TITLE
chore(demo): add links to other demos

### PR DESCRIPTION
**Pull request by UziTech**
## Description

Add links to the CommonMark and Daring Fireball demos from our demo page so it is easy to compare.

image

## Contributor

- [ ] Test(s) exist to ensure functionality and minimize regression (if no tests added, list tests covering this PR); or,
- [x] no tests required for this PR.
- [ ] If submitting new feature, it has been documented in the appropriate places.

## Committer

In most cases, this should be a different person than the contributor.

- [ ] CI is green (no forced merge required).
- [ ] Squash and Merge PR following [conventional commit guidelines](https://www.conventionalcommits.org/).

### CODE REVIEW

**Review by calculuschild — APPROVED** [review]
Good idea. I like it.

**Review by styfle — APPROVED** [review]
Sounds good, I think we could also make these links pass the markdown text too

**Comment by UziTech** [comment]
@styfle we can pass it to commonmark but I don't think there is a way to pass it to daring fireball. I thought about that but I didn't think it was that difficult to just copy/paste if that is what the user wanted to do.

**Comment by UziTech** [comment]
I'm just going to merge this as is and we can find a way to pass the markdown later if we want to.

**Pull request merged**
