### PR TITLE
docs: added copy to clipboard for each code block

### LINKED ISSUE #2611: add copy to clipboard for each code block
**Describe the feature**
I want to add copy to clipboard feature for each code block.

**Why is this feature necessary?**
as [#2365](https://github.com/markedjs/marked/issues/2365) explained, this feature makes it easier to copy content and also adds a good impression in terms of user experience.

### PR DESCRIPTION
**Pull request by danangtomo**
**Marked version:**

**Markdown flavor:** Markdown.pl|CommonMark|GitHub Flavored Markdown|n/a

## Description

- Fixes #2611 

## Expectation

Can do the copy process for each code block

## Result

image

## What was attempted

added copy to clipboard feature for each code block

## Committer

In most cases, this should be a different person than the contributor.

- [x] CI is green (no forced merge required).
- [x] Squash and Merge PR following [conventional commit guidelines](https://www.conventionalcommits.org/).

### CODE REVIEW

**Comment by danangtomo** [comment]
can you check it @UziTech

**Comment by UziTech** [comment]
I'll take a closer look at this in the next few days. Is there a reason you went with `execCommand` instead of `navigator.clipboard`?

**Comment by danangtomo** [comment]
> I'll take a closer look at this in the next few days. Is there a reason you went with `execCommand` instead of `navigator.clipboard`?

Please check the latest changes

**Comment by UziTech** [comment]
I think it would be better if the button would be on the top right instead of bottom right. That way it can be used without having to scroll to the bottom. Also it should be absolute positioned and show on hover like github.

code_copy

**Comment by danangtomo** [comment]
> I think it would be better if the button would be on the top right instead of bottom right. That way it can be used without having to scroll to the bottom. Also it should be absolute positioned and show on hover like github.
> 
> code_copy [ code_copy ](https://user-images.githubusercontent.com/97994/198518366-def45daa-cf00-4d27-b49e-029a60f13b43.gif) [ ](https://user-images.githubusercontent.com/97994/198518366-def45daa-cf00-4d27-b49e-029a60f13b43.gif)

Thanks for the input. changes have been made

**Comment by UziTech** [comment]
It looks like the wrapper div is taking up space. Can we absolute position that instead?

image

**Comment by UziTech** [comment]
I create a PR for this PR at https://github.com/danangtomo/marked/pull/1 If you merge that it will update this PR and I can approve it.

**Comment by danangtomo** [comment]
> I create a PR for this PR at [danangtomo#1](https://github.com/danangtomo/marked/pull/1) If you merge that it will update this PR and I can approve it.

cool. sorry I've been busy lately

**Review by UziTech — APPROVED** [review]
image

Thanks for working on this! 💯

**Comment by danangtomo** [comment]
> image [ image ](https://user-images.githubusercontent.com/97994/198940271-15c31610-eab6-45ce-9793-5cd9224c59ca.gif) [ ](https://user-images.githubusercontent.com/97994/198940271-15c31610-eab6-45ce-9793-5cd9224c59ca.gif)
> 
> Thanks for working on this! 💯

my pleasure. happy to have contributed!

**Comment by khanrahim1616** [comment]
Is there any code example of how to add / use copy to clipboard button ?

**Pull request merged**
