### PR TITLE
Add select option in demo mode to choose Marked version

### PR DESCRIPTION
**Pull request by remyhunt**
Demo selector Enhancement requested in #1406 

@styfle can you please take a look and please help me understand what the Snyk issue might be?

### CODE REVIEW

**Comment by UziTech** [comment]
The snyk issue is not related to your PR

**Comment by UziTech** [comment]
This doesn't seem to work. How have you tested it?

**Comment by styfle** [comment]
Can you dynamically load the version selector instead of yard code? We don’t want to have to update this code every time we release a new version. 

You can find published versions here:

https://registry.npmjs.com/marked

**Comment by UziTech** [comment]
https://github.com/remyhunt/marked/pull/1/ should work.

You can check it out [here](https://docs-9ga01flnm.now.sh/demo/?outputType=html&text=%23%20hi%0A%0A%23%20hi&options=%7B%0A%20%22baseUrl%22%3A%20null%2C%0A%20%22breaks%22%3A%20false%2C%0A%20%22gfm%22%3A%20true%2C%0A%20%22headerIds%22%3A%20true%2C%0A%20%22headerPrefix%22%3A%20%22%22%2C%0A%20%22highlight%22%3A%20null%2C%0A%20%22langPrefix%22%3A%20%22language-%22%2C%0A%20%22mangle%22%3A%20true%2C%0A%20%22pedantic%22%3A%20false%2C%0A%20%22sanitize%22%3A%20false%2C%0A%20%22sanitizer%22%3A%20null%2C%0A%20%22silent%22%3A%20false%2C%0A%20%22smartLists%22%3A%20false%2C%0A%20%22smartypants%22%3A%20false%2C%0A%20%22tables%22%3A%20true%2C%0A%20%22xhtml%22%3A%20false%0A%7D&version=0.5.2)

Change the version to 0.6.0 and the ids will use slugger to prevent collisions

**Pull request merged**
