### PR TITLE
Em less than 3 chars

### LINKED ISSUE #1178: Specific character combination not rendered correctly
**Marked version:** 0.3.19

**Markdown flavor:** n/a

## Expectation

`marked('_in_')` would be rendered as `<p><em>in</em></p>`.

## Result

`marked('_in_')` is rendered as `<p>_in_</p>`.

## What was attempted

`marked('_in_')`

Other combinations of `marked('_some string_')` appear to work as expected (certainly didn't run an exhaustive check).

### PR DESCRIPTION
**Pull request by UziTech**
**Marked version:** 84894118873d616c085f216a2d818c761f0592be

## Description

- Fixes #1178 

## Contributor

- [x] Test(s) exist to ensure functionality and minimize regression (if no tests added, list tests covering this PR)

## Committer

In most cases, this should be a different person than the contributor.

- [ ] Draft GitHub release notes have been updated.
- [x] CI is green (no forced merge required).
- [x] Merge PR

### CODE REVIEW

**Comment by Feder1co5oave** [comment]
Lgtm

**Comment by UziTech** [comment]
I added some edge cases like:

```
**1* => <p><em>*1</em></p>
```

This required adding more capturing parentheses so we could run into another problem like https://github.com/markedjs/marked/pull/1013#discussion_r168971826

**Comment by UziTech** [comment]
@joshbruce do we want to risk a breaking change like #1059 or wait for this fix til 0.4.x?

**Comment by joshbruce** [comment]
@UziTech: Think this is like #1203 and should come along with a 0.4.x release. We've done a lot of work around DevOps and even adding a couple of features. Given the number of people apparently losing Marked, we haven't received that much negative feedback re semver all things considered.

**Comment by Feder1co5oave** [comment]
Did you disable CI?

**Comment by styfle** [comment]
CI is running for other PRs, but I don't see this one: https://travis-ci.org/markedjs/marked/pull_requests

**Comment by UziTech** [comment]
That's weird, I swear it was there initially

**Comment by re-fort** [comment]
I'm looking forward to the next release included this fix:laughing:

**Comment by styfle** [comment]
@re-fort Definitely! We are waiting for a couple more fixes to land before we release verison 0.4.0.

**Pull request merged**
