### PR TITLE
CM Example 332

### PR DESCRIPTION
**Pull request by joshbruce**
**Marked version:** 0.3.17

**Markdown flavor:** CommonMark

Just realized, I actually don't know which flavor this is. While we say we support CommonMark, I am not explicitly setting the flavor using front matter. GFM *is* CommonMark with some extensions...anyway, gotta go.

## Expectation

```
<p>a * foo bar*</p>
```

## Result

```
<p>a*foobar*</p>
```

## What was attempted

```
a * foo bar*
```

## Contributor

- [ ] Test(s) exist to ensure functionality and minimize regresstion (if no tests added, list tests covering this PR); or,
- [ ] no tests required for this PR.
- [ ] If submitting new feature, it has been documented in the appropriate places.

## Committer

In most cases, this should be a different person than the contributor.

- [ ] Draft GitHub release notes have been updated.
- [ ] CI is green (no forced merge required).
- [ ] Merge PR

### CODE REVIEW

**Comment by joshbruce** [comment]
@styfle: Think we should consider reordering the PR template...

1. (What I) Attempted
2. (What I) Expected
3. (I) Got

**Comment by styfle** [comment]
I think what you are describing fits for describing a bug template not a PR. I would expect a PR to fix to a reported bug and just link back to it.

**Comment by styfle** [comment]
Also this PR is failing CI

**Comment by joshbruce** [comment]
@styfle: Thanks...I thought so as well but wasn't what I was told.

I got an:

- As a contributor...
- As an admin...

Story to explain how to this kinda hybrid action.

Let's make a new epic for 0.x - number 1 priority.

**Comment by joshbruce** [comment]
See #1159

**Pull request closed without merging**
