### PR TITLE
Release v0.5.2

### PR DESCRIPTION
**Pull request by styfle**
## Publisher

- [x] `$ npm version` has been run.
- [x] Release notes in [draft GitHub release](https://github.com/markedjs/marked/releases) are up to date
- [x] Release notes include which flavors and versions of Markdown are supported by this release
- [x] Committer checklist is complete.
- [x] Merge PR.
- [ ] Publish GitHub release using `master` with correct version number.
- [ ] `$ npm publish` has been run.
- [ ] Create draft GitHub release to prepare next release.

Note: If merges to `master` occur after submitting this PR and before running `$ npm pubish` you should be able to

1. pull from `upstream/master` (`git pull upstream master`) into the branch holding this version,
2. run `$ npm run build` to regenerate the `min` file, and
3. commit and push the updated changes.

## Committer

In most cases, this should be someone different than the publisher.

- [x] Version in `package.json` has been updated (see [PUBLISHING.md](https://github.com/markedjs/marked/blob/master/docs/PUBLISHING.md)).
- [x] The `marked.min.js` has been updated; or,
- [x] release does not change library.
- [x] CI is green (no forced merge required).

### CODE REVIEW

**Comment by styfle** [comment]
Looks like jasmine broke compatibility with older versions of node recently.

I created a PR but I'm not sure many packages support Node < v4

https://github.com/jasmine/jasmine-npm/pull/144

**Comment by UziTech** [comment]
looks like tests are failing because Jasmine just released v3.3.0 which is not compatible with node v0.10

we could fix this by pinning our jasmine dev dependency to v3.2.0 or remove node v0.10 from travis

**Comment by UziTech** [comment]
to be honest if any of our dependents are still using node v0.10 they are probably the ones pinning their marked dependency to [0.3.6](https://libraries.io/npm/marked/usage)

**Comment by UziTech** [comment]
according to https://libraries.io/npm/marked/usage we have less than 400 dependents using >=0.5.0

**Comment by styfle** [comment]
# Release Notes

## Bug Fixes

- Fix emphasis closing by single _ (part of left-flanking run) #1351 
- Make URL handling consistent between links and images #1359

## Other

- Add missing semicolons, add lint rule #1340
- Make Steven (@styfle) a npm publisher #1346 
- Fix typo in docs: re*s*ponsibility #1364
- Add the ability to specify options on the [demo page](https://marked.js.org/demo/) as JSON #1357 
    - Show red border when JSON options are invalid #1360
- Move license file back to root dir #1356
- Fix builds: remove node v0.10 from travis matrix #1366
    - This does not a break compatibility in this release but it will a future release
- Add `files` key to package.json to prevent publishing unused files #1367

**Comment by styfle** [comment]
Boom 💣 

https://www.npmjs.com/package/marked/v/0.5.2

**Pull request merged**
