### PR TITLE
Add marked mark maker badge

### PR DESCRIPTION
**Pull request by joshbruce**
**Marked version:** 0.3.17

**Markdown flavor:** n/a

## Description

Adds `Maker of the Marked mark` badge

## Contributor

- [ ] Test(s) exist to ensure functionality and minimize regresstion (if no tests added, list tests covering this PR); or,
- [x] no tests required for this PR.
- [ ] If submitting new feature, it has been documented in the appropriate places.

## Committer

In most cases, this should be a different person than the contributor.

- [ ] Draft GitHub release notes have been updated.
- [ ] CI is green (no forced merge required).
- [ ] Merge PR

### CODE REVIEW

**Comment by styfle** [comment]
@joshbruce Before you go changing the docs, can we land https://github.com/markedjs/marked/pull/1138 first?

**Comment by joshbruce** [comment]
Good question. Yes.

I was only adding runway to let you run with it by making putting up for being an admin...I don’t think anyone would be opposed to you being the second admin.

Leave it to the team on this one.

**Comment by joshbruce** [comment]
The next PR I submit will be take move you to admin and let everyone review.

**Comment by styfle** [comment]
Ok I merged #1138 and this created merged conflicts with your PR as I expected.

**Comment by joshbruce** [comment]
@UziTech and @UziTech: Think I resolved this properly.

**Comment by joshbruce** [comment]
@markedjs/marked: Merging to move forward on community building todo list.

**Pull request merged**
