### PR TITLE
commonmark.0.29.json

### PR DESCRIPTION
**Pull request by Pratik-ahirrao**
changed "shouldFail": true to "shouldFail": false

**Marked version:**

**Markdown flavor:** Markdown.pl|CommonMark|GitHub Flavored Markdown|n/a

## Description

- Fixes #### (if fixing a known issue; otherwise, describe issue using the following format)

## Contributor

- [ ] Test(s) exist to ensure functionality and minimize regression (if no tests added, list tests covering this PR); or,
- [ ] no tests required for this PR.
- [ ] If submitting new feature, it has been documented in the appropriate places.

## Committer

In most cases, this should be a different person than the contributor.

- [ ] Draft GitHub release notes have been updated.
- [ ] CI is green (no forced merge required).
- [ ] Merge PR

### CODE REVIEW

**Comment by Pratik-ahirrao** [comment]
PR has been failed . What should i do now?

**Comment by UziTech** [comment]
You should try to only fix one or a few tests at a time. When you change a test from `shouldFail: true` to `shouldFail: false` it will fail the test. You will then have to change the code in the `src` folder to get it to pass.

If you have node setup on your local machine you can run `npm test` in the directory where you cloned marked to see if the tests pass. Once they pass on your local machine you can create a new PR for those fixes.

If you have any issues setting it up on your local computer just let us know and we would be happy to help.

**Comment by Pratik-ahirrao** [comment]
what should be the correct output?
if all shouldFail is true, then i am getting this output:-
1538 specs, 0 failures
Finished in 2.406 seconds
Randomized with seed 33404 (jasmine --random=true --seed=33404)

**Comment by UziTech** [comment]
`0 failures` is the correct output.

The `shouldFail` property tells the test framework that we know that spec is failing so if it fails it passes the test. When you change `shouldFail` to `false` you are telling the test framework to mark it as a failure if that test fails.

The ultimate goal is to have all tests passing with `shouldFail: false`.

**Comment by Pratik-ahirrao** [comment]
I have changed one true to false. I am getting this output:-
CommonMark Tabs should pass example 7
  Message:
    Expected: <ul><li><pre><code>foo</code></pre></l
      Actual: <ul><li>foo</li></ul>
  Stack:
    Error
        at <Jasmine>
        at UserContext.<anonymous> (/home/pratik/Desktop/marked-master/test/specs/run-spec.js:36:39)
        at <Jasmine>
        at runCallback (timers.js:794:20)
Why is it so?

**Comment by UziTech** [comment]
Because there is an error in the way marked parses that markdown. Now you will have to change one of the files in the `src` directory to make the tests say `0 failures` again.

**Pull request closed without merging**
