### PR TITLE
use latest commit for demo master

### PR DESCRIPTION
**Pull request by UziTech**
## Description

use `@master` in demo for master version

https://docs-ikjy0vxvf.now.sh/demo/

- fixes comment https://github.com/markedjs/marked/issues/1456#issuecomment-478090870

## Contributor

- [x] no tests required for this PR.

## Committer

In most cases, this should be a different person than the contributor.

- [ ] Draft GitHub release notes have been updated.
- [ ] CI is green (no forced merge required).
- [ ] Merge PR

### CODE REVIEW

**Comment by styfle** [comment]
I think the branch is cached by the CDN for a week or so which is maybe why it wasn’t showing the latest.

**Comment by UziTech** [comment]
If that is the case than this won't fix the issue. I wonder If I should grab the latest commit hash and use that.

**Comment by styfle** [comment]
@UziTech That might work. Another alternative is to add a "bust cache" button since there appears to be an [API](https://github.com/jsdelivr/jsdelivr#purge-cache) for that (requires an email).

See the full discussion here: https://github.com/jsdelivr/jsdelivr/issues/18101

**Comment by UziTech** [comment]
Using the latest commit hash seems to be the right way to go.

https://docs-qaob045da.now.sh/demo/

**Comment by UziTech** [comment]
I also fixed a bug when using a regular version

https://docs-ikjy0vxvf.now.sh/demo

**Pull request merged**
