### PR TITLE
[WIP] add options to demo page

### PR DESCRIPTION
**Pull request by UziTech**
## Description

Adds options to the demo page so users can set the `gfm`, `pedantic`, or `smartypants` options

image

The question mark next to the spec links to the spec they selected.

The question mark next to smartypants links to the smartypants docs

Also adds the marked version to the title

## Contributor

- [ ] Test(s) exist to ensure functionality and minimize regression (if no tests added, list tests covering this PR); or,
- [x] no tests required for this PR.
- [ ] If submitting new feature, it has been documented in the appropriate places.

## Committer

In most cases, this should be a different person than the contributor.

- [ ] Draft GitHub release notes have been updated.
- [ ] CI is green (no forced merge required).
- [ ] Merge PR

### CODE REVIEW

**Comment by styfle** [comment]
@UziTech What's left to do for this one?

**Comment by UziTech** [comment]
I wanted to figure out a way to add all the options without just crowding the top with check boxes but haven't had time to work on it

**Comment by styfle** [comment]
Maybe a solution could be to expose the default options as JSON and let the user edit as text? That way the demo is always configurable, even when we add a new option.

**Comment by UziTech** [comment]
That sounds good. Should I add a drop-down pane for options?

**Comment by styfle** [comment]
Sure

**Comment by UziTech** [comment]
closed by #1357

**Pull request closed without merging**
