### PR TITLE
Release 0.6.2

### PR DESCRIPTION
**Pull request by styfle**
## Publisher

- [x] `$ npm version` has been run.
- [x] Release notes in [draft GitHub release](https://github.com/markedjs/marked/releases) are up to date
- [x] Release notes include which flavors and versions of Markdown are supported by this release
- [x] Committer checklist is complete.
- [x] Merge PR.
- [x] Publish GitHub release using `master` with correct version number.
- [ ] `$ npm publish` has been run.
- [ ] Create draft GitHub release to prepare next release.

Note: If merges to `master` occur after submitting this PR and before running `$ npm pubish` you should be able to

1. pull from `upstream/master` (`git pull upstream master`) into the branch holding this version,
2. run `$ npm run build` to regenerate the `min` file, and
3. commit and push the updated changes.

## Committer

In most cases, this should be someone different than the publisher.

- [x] Version in `package.json` has been updated (see [PUBLISHING.md](https://github.com/markedjs/marked/blob/master/docs/PUBLISHING.md)).
- [x] The `marked.min.js` has been updated; or,
- [x] release does not change library.
- [x] CI is green (no forced merge required).

### CODE REVIEW

**Comment by UziTech** [comment]
I would like to get #1438 and #1439 merged before this release

**Comment by styfle** [comment]
@UziTech Would you consider both #1438 and #1439 semver patches?

The changes we've merged so far were fixes for regressions so I feel like we can ship a patch asap for the Node Docs team.

/cc @joshbruce

**Comment by UziTech** [comment]
Ya they are definitely patches. They both fix rare conditions that would be considered broken if anyone stumbled upon them.

**Comment by styfle** [comment]
@UziTech Is this still considered a patch release?

## Security

- Link redos #1426 

## Fixes

- Links parens #1435 
- New line after table with escaped pipe #1439 
- List item tables #1446 

## Enhancements

- Pass token boolean to the `listitem` function #1440
- Allow html without \n after #1438

## CLI

- Update man page to include `--test` and fix argv parameters #1442 
- Add a `--version` flag to print marked version #1448

## Testing

- Normalize marked tests #1444 
- Update tests to node 4 syntax #1449

**Comment by UziTech** [comment]
I think it still is a patch release. I don't see anything that will break current workflows.

**Comment by UziTech** [comment]
@davisjam @joshbruce can we get another approval so we can release a new version?

**Comment by styfle** [comment]
Published as `0.6.2`: https://github.com/markedjs/marked/releases/tag/v0.6.2

**Pull request merged**
