### PR TITLE
Docs navigation

### PR DESCRIPTION
**Pull request by UziTech**
**Marked version:** latest

**Markdown flavor:** Markdown.pl|CommonMark|GitHub Flavored Markdown|n/a

## Description

This PR adds a ribbon that links to the github repo and adds a link to marked icon back to the README.md

image

## Contributor

- [ ] Test(s) exist to ensure functionality and minimize regresstion (if no tests added, list tests covering this PR); or,
- [x] no tests required for this PR.
- [ ] If submitting new feature, it has been documented in the appropriate places.

## Committer

In most cases, this should be a different person than the contributor.

- [ ] Draft GitHub release notes have been updated.
- [x] CI is green (no forced merge required).
- [x] Merge PR

### CODE REVIEW

**Comment by UziTech** [comment]
We should probably also make a way to be able to link to different parts of the site.

Because this is a SPA there is no way to view AUTHORS.md without clicking on a link in https://marked.js.org/

**Comment by joshbruce** [comment]
@UziTech: I was wondering if a SPA would be the desired approach or not. Namely because of the double-anchor problem. /# (makes it a SPA) /#something#inline (becomes a different problem to solve).

One way to do it would be to use multiple index.html file within directories. Or, use something like VueJS or Angular.

**Comment by joshbruce** [comment]
Would also be nice if the README still linked to different documents. Like having two links in the usage section - one to the advanced and another to the pro.

**Comment by UziTech** [comment]
> Namely because of the double-anchor problem.

Ya I through together a `hashchange` router at https://github.com/UziTech/marked/commit/62b697afb09ced16e7dafbf222f4b61a5817f807 but it has some problems with the back and forward buttons.

I'm thinking the index files in directories would be a better solution

**Comment by styfle** [comment]
I was thinking of doing something like using urls like `marked.js.org/#page=AUTHORS.md` which would render the AUTHORS.md file as html.

This would give us a way to render additional non-docs pages that are not part of the docs SPA such as `marked.js.org/demo.html`...see this: https://github.com/markedjs/marked/pull/64

**Comment by joshbruce** [comment]
That alternative make my UX brain hiccup a bit...to computer, not enough human, if that makes sense. Same issues with `?p=5` from single-page server-side. We might be able to use just the router from something like Angular...that's all we're really looking for.

A router that doesn't break that back and forward buttons, while also allowing for inline anchors.

Still thinking the cheapest and easiest would be multiple index.html files:

```
/index.html <- readme with demo (that could be cool) see Haskell https://www.haskell.org
  /authors/index.html <- renders the md
  /code-of-conduct
  /contributing
  /publishing
  /using <- display readme again
    /advanced
    /pro
```

Just clean and simple human readable urls. Only drawback is that there would be some duplication of code...but I don't think it's that big of a deal for such a small static site.

??

**Comment by joshbruce** [comment]
Just realized the demo thing is what #64 is about. :)

**Comment by styfle** [comment]
Or we could avoid re-inventing the wheel and go with this: https://docsify.js.org

**Comment by joshbruce** [comment]
Interesting. Could we use Jekyll (native GitHub Pages). Given our current focus - we could use the marked site to showcase some of our personal projects...touching on the professional growth itch.

I've been working on a design system based on the [USWDS](https://github.com/uswds/uswds) for 8fold and the practitioner sites: https://www.npmjs.com/package/8fold-web-assets

Definitely thinking starting a separate repo would be good as well. I don't mind reimagining the wheel so long as it helps us grow professionally in an environment that's not mission critical to us eating. :)

**Pull request merged**
