### PR TITLE
Support math latex.

### PR DESCRIPTION
**Pull request by ahuigo**
**Marked version:**
Release 0.4.0

## Contributor
I don't know how to test this project exactly. Any advice?

- [x] Test(s) exist to ensure functionality and minimize regression (if no tests added, list tests covering this PR); or,
- [ ] no tests required for this PR.
- [x] If submitting new feature, it has been documented in the appropriate places.

The demo for this feature:
> https://github.com/ahuigo/marked/blob/master/docs/demo/latex.html

## Committer

In most cases, this should be a different person than the contributor.

- [ ] Draft GitHub release notes have been updated.
- [ ] CI is green (no forced merge required).
- [ ] Merge PR

### CODE REVIEW

**Comment by ahuigo** [comment]
@UziTech  
It's hard to add a wrapper for marked. I have to add a math lexer to marked.( If user want to parse math, he should pass option `latexParser`).  

1. I wish marked itself would support math lexer, because many people need math latex.
2. If I create a  separate npm, it was hard to pull code back to upstream , as I have changed marked's lexer directly.

**Comment by UziTech** [comment]
We are trying to [slim marked down](https://github.com/markedjs/marked/issues/302). By the 1.0 release we would like to deprecate most of the options.

We are trying to focus on making marked spec compliant with CommonMark and GFM. For everything else we would like to create separate modules that extend marked.

I can leave this PR open so we can revisit it in the future and possibly create a module ourselves but it will be a while before that happens.

**Comment by BenjaminHoegh** [comment]
Is there a API for marked or is it code it from the ground if you wanna make extensions to it?

**Comment by BenjaminHoegh** [comment]
@UziTech Posible without node.js? Some web hotels don't support nodejs and would like to keep it working on so many server types as possible

**Comment by UziTech** [comment]
@BenjaminHoegh Is what possible without node? marked is written in js so it needs a js engine in order to run at all.

If you use marked on the client side it will create a global variable `marked` so you just replace `var myMarked = require('marked');` with `var myMarked = marked;`

**Comment by BenjaminHoegh** [comment]
@UziTech Is there documentation about how to add new rules to inline and block

**Comment by UziTech** [comment]
I don't believe there is a way to add **new** rules easily yet. All of our documentation is as [marked.js.org ](https://marked.js.org)

**Comment by yhcharles** [comment]
@ahuigo 
It seems the blocklatex is rendering in display mode.

**Comment by ahuigo** [comment]
@yhcharles What you need is `\displaystyle` , for example`$\displaystyle \sum_i^j$`.  You can try it  here: https://ahuigo.github.io/a/md.html

**Comment by BrianHung** [comment]
@yhcharles 

This is a bit late, but another solution would be to change the source code beginning at line 935 from
```javascript
      var html = marked.defaults.latexRender(text);
      if (block) {
        out = '<div style="text-align:center">' + html + '</div>';
      }else{
        out = html;
      }
```

to
```javascript
      if (block) {
        out = marked.defaults.latexRender(text, {displayMode: true});
      }else{
        out = marked.defaults.latexRender(text);
      }
```

This assumes you're using KaTeX to render LaTeX; documentation [here](https://katex.org/docs/options.html). I'm sure that MathJax has the same setting.

Note I haven't tested this implementation yet.

**Pull request closed without merging**
