### PR TITLE
Release 0.5.1

### PR DESCRIPTION
**Pull request by joshbruce**
## Publisher

- [x] `$ npm version` has been run.
- [x] Release notes in [draft GitHub release](https://github.com/markedjs/marked/releases) are up to date
- [ ] Release notes include which flavors and versions of Markdown are supported by this release
- [x] Committer checklist is complete.
- [ ] Merge PR.
- [ ] Publish GitHub release using `master` with correct version number.
- [ ] `$ npm publish` has been run.
- [ ] Create draft GitHub release to prepare next release.

Note: If merges to `master` occur after submitting this PR and before running `$ npm pubish` you should be able to

1. pull from `upstream/master` (`git pull upstream master`) into the branch holding this version,
2. run `$ npm run build` to regenerate the `min` file, and
3. commit and push the updated changes.

## Committer

In most cases, this should be someone different than the publisher.

- [x] Version in `package.json` has been updated (see [PUBLISHING.md](https://github.com/markedjs/marked/blob/master/docs/PUBLISHING.md)).
- [x] The `marked.min.js` has been updated; or,
- [x] release does not change library.
- [x] CI is green (no forced merge required).

### CODE REVIEW

**Comment by joshbruce** [comment]
We should reconsider this in the checklist for releases. I really like the evolution of the release notes so far, really helps me know what type of version number to use. But, I don't know how much value the markdown flavor will have - nobody has really requested it since whoever it was made me think it would be a good idea...or I'm blind at it is there (been rough).

"Release notes include which flavors and versions of Markdown are supported by this release"

**Comment by UziTech** [comment]
Shouldn't this be 0.5.1 I don't think there were any breaking changes or new features added since the last release.

**Comment by joshbruce** [comment]
The **Major** heading means we would be doing a major release, if we weren't on the zero-major, yeah (good UX, btw)? So, it would be 0.6.0. If everything was under **Minor** then it would be 0.5.1, yeah?

**Comment by styfle** [comment]
I'm fine with this release being 0.5.1

**Comment by UziTech** [comment]
I guess every fix could break someones [workflow](https://xkcd.com/1172/) 🤣

**Comment by styfle** [comment]
@joshbruce I updated the [release notes](https://github.com/markedjs/marked/releases) to use the name `0.5.1` instead. Would you like to fix this branch or make a new one?

**Comment by joshbruce** [comment]
@styfle: 

Tempted just to ship it as 0.6.0 - lazy, but feeling much better.  lol

Probably keep the same branch, the only thing running `nom version` doesn't really do much: https://docs.npmjs.com/cli/version - we can delete after the merge.

Probably keep the same PR as well, change the name.

In the future, here's how my brain is working, just to make sure:

- If there's anything under the `major` heading in the release notes, gonna do a minor while under the zero-major.
- If there's anything under the `minot` or `patch` heading, gonna do a patch while under the zero-major.

This one's free to be weird, we'll get it sorted. 😂

**Comment by joshbruce** [comment]
ps. Still think the major, minor, patch idea was pretty brilliant. Having said that, probably helped us more than the users.

**Comment by styfle** [comment]
> lazy, but feeling much better. lol

@joshbruce Glad you're feeling better. If you want to take it easy and give publish permission to UziTech or myself, then we can step in when you are unavailable to avoid blocking releases.

**Comment by joshbruce** [comment]
@styfle: Thanks for asking. Will put together a couple of PRs using the template per the process of changing things. :)

Or you and @UziTech could do it as well.

Now that things seem relatively stable with the crew I don't have concerns around it like I did before.

**Comment by joshbruce** [comment]
Ah, never mind...didn't notice that in the authors page changes. We've kinda lost the roadmap to people to contact for what, which was one of the first things brought up by @davisjam before he became part of the team. @styfle you okay letting me trying some stuff? I will do my best to incorporate both of our concepts; or, we can straight up collab on it.

**Comment by joshbruce** [comment]
@styfle: Just to make sure I'm following and making clear the idea and current process.

1. Authors page: Would like to make modifications re the HTML and layout of "the cards". 

2. Making people owners on the package: We have a process in place for publicly requesting or recommending changing someone's status in the project via PRs (this way it's transparent to the community - I'm big on transparency https://github.com/markedjs/marked/pull/1150). [See badges template](https://github.com/markedjs/marked/blob/master/.github/PULL_REQUEST_TEMPLATE/badges.md)

Which (or both) are you thinking should be handled in the org chat.

**Comment by UziTech** [comment]
marked could also be moved under the [@markedjs](https://www.npmjs.com/org/markedjs) org on npm

**Comment by joshbruce** [comment]
@UziTech: I don't have an issue with that. Think we talked about doing that before and decided against an org in NPM. Not saying things can't change, just can't remember *why* we had decided not to - make sure we're not forgetting a dealbreaker.

**Comment by styfle** [comment]
> marked could also be moved under the @markedjs org on npm

As far as I know, moving to an org would force all dependents to change their `package.json` to reference the new package. I don't believe there is such a thing as aliasing packages and I don't think it would be a good idea to publish to two packages. Instead, we could publish to the org and deprecate the old.

That might make more sense for v1.0.0 along with splitting out the CLI (which would be a breaking change).

- `@markedjs/marked`
- `@markedjs/cli`
- `@markedjs/html-differ`

**Comment by UziTech** [comment]
Moving to an org doesn't mean the package would need to be namespaced. I have almost all of my npm packages in the [UziTech](https://www.npmjs.com/org/uzitech) org but none of them are namespaced.

I believe the packages can only be namespaced if they are part of an org though.

I do think the community is moving toward namespacing packages so they are harder to impersonate.

I agree this would be a good thing to do in v1.0.0

**Comment by styfle** [comment]
Well that's new to me! I like it, let's do that! 👍

**Pull request merged**
