### PR TITLE
nested parentheses link

### LINKED ISSUE #1405: Too many a tag, the CPU will be 100% when there is no split
**Describe the bug**
Too many a tag, the CPU will be 100% when there is no split.

**To Reproduce**

md is:
```
* 伪类：[:active](https://developer.mozilla.org/en-US/docs/Web/CSS/:active)、[:any-link](https://developer.mozilla.org/en-US/docs/Web/CSS/:any-link)、[:blank](https://developer.mozilla.org/en-US/docs/Web/CSS/:blank)、[:checked](https://developer.mozilla.org/en-US/docs/Web/CSS/:checked)、[:current](https://developer.mozilla.org/en-US/docs/Web/CSS/:current)、[:default](https://developer.mozilla.org/en-US/docs/Web/CSS/:default)、[:defined](https://developer.mozilla.org/en-US/docs/Web/CSS/:defined)、[:dir()](https://developer.mozilla.org/en-US/docs/Web/CSS/:dir)、[:disabled](https://developer.mozilla.org/en-US/docs/Web/CSS/:disabled)、[:drop](https://developer.mozilla.org/en-US/docs/Web/CSS/:drop)、[:empty](https://developer.mozilla.org/en-US/docs/Web/CSS/:empty)、[:enabled](https://developer.mozilla.org/en-US/docs/Web/CSS/:enabled)、[:first](https://developer.mozilla.org/en-US/docs/Web/CSS/:first)、[:first-child](https://developer.mozilla.org/en-US/docs/Web/CSS/:first-child)、[:first-of-type](https://developer.mozilla.org/en-US/docs/Web/CSS/:first-of-type)、[:fullscreen](https://developer.mozilla.org/en-US/docs/Web/CSS/:fullscreen)、[:future](https://developer.mozilla.org/en-US/docs/Web/CSS/:future)、[:focus](https://developer.mozilla.org/en-US/docs/Web/CSS/:focus)、[:focus-visible](https://developer.mozilla.org/en-US/docs/Web/CSS/:focus-visible)、[:focus-within](https://developer.mozilla.org/en-US/docs/Web/CSS/:focus-within)、[:has()](https://developer.mozilla.org/en-US/docs/Web/CSS/:has)、[:host](https://developer.mozilla.org/en-US/docs/Web/CSS/:host)、[:host()](https://developer.mozilla.org/en-US/docs/Web/CSS/:host())、[:host-context()](https://developer.mozilla.org/en-US/docs/Web/CSS/:host-context())、[:hover](https://developer.mozilla.org/en-US/docs/Web/CSS/:hover)、[:indeterminate](https://developer.mozilla.org/en-US/docs/Web/CSS/:indeterminate)、[:in-range](https://developer.mozilla.org/en-US/docs/Web/CSS/:in-range)、[:invalid](https://developer.mozilla.org/en-US/docs/Web/CSS/:invalid)、[:is()](https://developer.mozilla.org/en-US/docs/Web/CSS/:is)、[:lang()](https://developer.mozilla.org/en-US/docs/Web/CSS/:lang)、[:last-child](https://developer.mozilla.org/en-US/docs/Web/CSS/:last-child)、[:last-of-type](https://developer.mozilla.org/en-US/docs/Web/CSS/:last-of-type)、[:left](https://developer.mozilla.org/en-US/docs/Web/CSS/:left)、[:link](https://developer.mozilla.org/en-US/docs/Web/CSS/:link)、[:local-link](https://developer.mozilla.org/en-US/docs/Web/CSS/:local-link)、[:not()](https://developer.mozilla.org/en-US/docs/Web/CSS/:not)、[:nth-child()](https://developer.mozilla.org/en-US/docs/Web/CSS/:nth-child)、[:nth-col()](https://developer.mozilla.org/en-US/docs/Web/CSS/:nth-col)、[:nth-last-child()](https://developer.mozilla.org/en-US/docs/Web/CSS/:nth-last-child)、[:nth-last-col()](https://developer.mozilla.org/en-US/docs/Web/CSS/:nth-last-col)、[:nth-last-of-type()](https://developer.mozilla.org/en-US/docs/Web/CSS/:nth-last-of-type)、[:nth-of-type()](https://developer.mozilla.org/en-US/docs/Web/CSS/:nth-of-type)、[:only-child](https://developer.mozilla.org/en-US/docs/Web/CSS/:only-child)、[:only-of-type](https://developer.mozilla.org/en-US/docs/Web/CSS/:only-of-type)、[:optional](https://developer.mozilla.org/en-US/docs/Web/CSS/:optional)、[:out-of-range](https://developer.mozilla.org/en-US/docs/Web/CSS/:out-of-range)、[:past](https://developer.mozilla.org/en-US/docs/Web/CSS/:past)、[:placeholder-shown](https://developer.mozilla.org/en-US/docs/Web/CSS/:placeholder-shown)、[:read-only](https://developer.mozilla.org/en-US/docs/Web/CSS/:read-only)、[:read-write](https://developer.mozilla.org/en-US/docs/Web/CSS/:read-write)、[:required](https://developer.mozilla.org/en-US/docs/Web/CSS/:required)、[:right](https://developer.mozilla.org/en-US/docs/Web/CSS/:right)、[:root](https://developer.mozilla.org/en-US/docs/Web/CSS/:root)、[:scope](https://developer.mozilla.org/en-US/docs/Web/CSS/:scope)、[:target](https://developer.mozilla.org/en-US/docs/Web/CSS/:target)、[:target-within](https://developer.mozilla.org/en-US/docs/Web/CSS/:target-within)、[:user-invalid](https://developer.mozilla.org/en-US/docs/Web/CSS/:user-invalid)、[:valid](https://developer.mozilla.org/en-US/docs/Web/CSS/:valid)、[:visited](https://developer.mozilla.org/en-US/docs/Web/CSS/:visited)、[:where()](https://developer.mozilla.org/en-US/docs/Web/CSS/:where)
* 伪元素：[::after (:after)](https://developer.mozilla.org/en-US/docs/Web/CSS/::after)、[::backdrop](https://developer.mozilla.org/en-US/docs/Web/CSS/::backdrop)、[::before (:before)](https://developer.mozilla.org/en-US/docs/Web/CSS/::before)、[::cue (:cue)](https://developer.mozilla.org/en-US/docs/Web/CSS/::cue)、[::first-letter (:first-letter)](https://developer.mozilla.org/en-US/docs/Web/CSS/::first-letter)、[::first-line (:first-line)](https://developer.mozilla.org/en-US/docs/Web/CSS/::first-line)、[::grammar-error](https://developer.mozilla.org/en-US/docs/Web/CSS/::grammar-error)、[::marker](https://developer.mozilla.org/en-US/docs/Web/CSS/::marker)、[::placeholder](https://developer.mozilla.org/en-US/docs/Web/CSS/::placeholder)、[::selection](https://developer.mozilla.org/en-US/docs/Web/CSS/::selection)、[::slotted()](https://developer.mozilla.org/en-US/docs/Web/CSS/::slotted)、[::spelling-error](https://developer.mozilla.org/en-US/docs/Web/CSS/::spelling-error) 
```

**Expected behavior**
CPU is normal

### PR DESCRIPTION
**Pull request by UziTech**
**Marked version:** 0.6.0

## Description

This is my proposed fix for #1405. It works with allowing multiple nested parentheses.

fixes #1405 
closes #1408

## Contributor

- [x] Test(s) exist to ensure functionality and minimize regression (if no tests added, list tests covering this PR)

## Committer

In most cases, this should be a different person than the contributor.

- [ ] Draft GitHub release notes have been updated.
- [ ] CI is green (no forced merge required).
- [ ] Merge PR

### CODE REVIEW

**Comment by UziTech** [comment]
I'd like to get opinions from @Feder1co5oave and @davisjam on this approach.

**Comment by UziTech** [comment]
We should merge this soon and release a new version to fix https://snyk.io/vuln/SNYK-JS-MARKED-73637

**Comment by styfle** [comment]
@UziTech Why is this PR still failing snyk? (I can't actually see the Details when I click it)

**Comment by UziTech** [comment]
The snyk check is failing because of https://snyk.io/vuln/SNYK-JS-MARKED-73637

maybe we should disable that check since it seems to be more of a false positive on most PRs.

**Comment by styfle** [comment]
But enough people use snyk that its probably good to know when we are failing.

It sounds like the one thats failing is not related to this PR so I see why that's confusing.

**Comment by UziTech** [comment]
The Snyk Github integration matches package version and dependencies to vulnerabilities in their database.

Since there is a [vulnerability](https://snyk.io/vuln/SNYK-JS-MARKED-73637) in the current version of marked, all new PRs will fail the Snyk check.

Marked doesn't have any regular dependencies so the only thing the Snyk check will tell us is if the current version of marked has a vulnerability or if there is a vulnerability in one of our dev dependencies (neither of which I think is especially helpful to check on every new PR)

**Comment by Feder1co5oave** [comment]
Hi, this looks good to me, although I'm not sure escaping works as expected: can you verify inputs such as

```
[Text](uri\()
[Text](uri(\())
[Text](uri\\())
```
? Unfortunately I can't do it myself right now

**Comment by UziTech** [comment]
[demo](https://docs-8bxhez41v.now.sh/demo/?outputType=html&text=%5BText%5D(uri%5C()%0A%5BText%5D(uri(%5C())%0A%5BText%5D(uri%5C%5C())&options=&version=pr%3A1414)

it looks like it works

**Comment by UziTech** [comment]
If the function sees a `\` it just skips the next character

**Comment by styfle** [comment]
> only thing the Snyk check will tell us is if the current version of marked has a vulnerability

Let’s remove the Snyk check on PRs (I think @joshbruce has to disable it)

Maybe we should add the badge to the README 

 https://snyk.io/test/npm/marked/badge.svg

**Comment by joshbruce** [comment]
I'm fine with that - sounds argument from @UziTech and good suggestion from @styfle.

Can we also double check a few things on the GitHub operations front?

You both are admins.

1. You should have access to the settings tab + web hooks section. There you should be able to delete Snyk...could be wrong...just double checking.

2. We also have WIP inside the integrations area. Are folks using it (are they even away of it)? If not, makes me question its value. Further GitHub released the idea of draft PRs that kinda offer the same protection; therefore, thinking we should default to native experience over integrating a package: https://help.github.com/articles/about-pull-requests/#draft-pull-requests

Thoughts and feedback, as always, welcome.

**Comment by Feder1co5oave** [comment]
> [demo](https://docs-8bxhez41v.now.sh/demo/?outputType=html&text=%5BText%5D(uri%5C()%0A%5BText%5D(uri(%5C())%0A%5BText%5D(uri%5C%5C())&options=&version=pr%3A1414)
> 
> it looks like it works

I just noticed that page automatically redirects to `version=master`!
Checking out locally, it really seems working:

```
[Text](uri\()
[Text](uri(\())
[Text](uri\\())
[Text](uri\)\))
[Text](uri\(\(())
^D

<p><a href="uri(">Text</a>
<a href="uri(()">Text</a>
<a href="uri%5C()">Text</a>
<a href="uri))">Text</a></p>
<p><a href="uri((()">Text</a></p>
```

**Pull request merged**
