### PR TITLE
New line after table

### PR DESCRIPTION
**Pull request by UziTech**
**Marked version:** master

**Markdown flavor:** GitHub Flavored Markdown

## Description

Fixes new line after a table removing last `|`

## Contributor

- [x] Test(s) exist to ensure functionality and minimize regression

## Committer

In most cases, this should be a different person than the contributor.

- [ ] Draft GitHub release notes have been updated.
- [ ] CI is green (no forced merge required).
- [ ] Merge PR

### CODE REVIEW

**Comment by styfle** [comment]
There are some merge conflicts

**Comment by UziTech** [comment]
That is the issue with using a json file for all of the tests. Once one is merged all other PRs that add tests to that file will have a merge conflict.

**Comment by styfle** [comment]
And also json has to escape quotes and such 🙄

**Comment by styfle** [comment]
Is this use case in the spec?

**Comment by UziTech** [comment]
Yes, our implementation was only wrong when there is an escaped pipe in the table

**Pull request merged**
