### PR TITLE
Fix a bug in does not display of the table cell if it empty.

### LINKED ISSUE #188: Table parsing omits last row/last cell if only whitespace
Given the following markdown:

```
|                       | Do not Want | Sometimes | Always |
| --------------------- | ----------- | --------- | ------ | 
| Feature A |  |  |  |
| Feature B |  |  |  |
```

The following should be produced:

|  | Do not Want | Sometimes | Always |
| --- | --- | --- | --- |
| Feature A |  |  |  |
| Feature B |  |  |  |

Instead, the cells array omits the last column.

```
[ 'Feature A', '', '', '' ]
[ 'Feature B', '', '' ]
```

### LINKED ISSUE #476: Empty cell is not generated????
I have following mark down file which has a table, notice the 3rd column does not have value, and is empty

| Header1 | Header2 | Header3 | Header4 |
| :-- | :-: | :-- | :-- |
| value1 | value2 |  | value4 |

it generates following html, notice it has 3 cells, I would expect there is an empty <td></td> after value2.  Anyone know what could be issue here?

<table>
..............
<tbody>
<tr>
<td align="left">value1</td>
<td align="center">value2</td>
<td align="left">value4</td>
</tr>
</tbody>
</table>

### LINKED ISSUE #693: Tables: missing <td></td> at last field if it's empty?
Markdown code:

``` markdown
| Field       | Type             | Null | Key | Default             | Extra          |
|-------------|------------------|------|-----|---------------------|----------------|
| id          | int(10) unsigned | NO   | PRI | NULL                | auto_increment |
| email       | varchar(255)     | NO   | UNI | NULL                |                |
| password    | varchar(255)     | NO   |     | NULL                |                |
| permissions | text             | YES  |     | NULL                |                |
| last_login  | timestamp        | YES  |     | NULL                |                |
| first_name  | varchar(255)     | YES  |     | NULL                |                |
| last_name   | varchar(255)     | YES  |     | NULL                |                |
| created_at  | timestamp        | NO   |     | 0000-00-00 00:00:00 |                |
| updated_at  | timestamp        | NO   |     | 0000-00-00 00:00:00 |                |
```

Rendered HTML code:

``` html
<table>
<thead>
<tr>
<th>Field</th>
<th>Type</th>
<th>Null</th>
<th>Key</th>
<th>Default</th>
<th>Extra</th>
</tr>
</thead>
<tbody>
<tr>
<td>id</td>
<td>int(10) unsigned</td>
<td>NO</td>
<td>PRI</td>
<td>NULL</td>
<td>auto_increment</td>
</tr>
<tr>
<td>email</td>
<td>varchar(255)</td>
<td>NO</td>
<td>UNI</td>
<td>NULL</td>
<td></td>
</tr>
<tr>
<td>password</td>
<td>varchar(255)</td>
<td>NO</td>
<td></td>
<td>NULL</td>
<td></td>
</tr>
<tr>
<td>permissions</td>
<td>text</td>
<td>YES</td>
<td></td>
<td>NULL</td>
<td></td>
</tr>
<tr>
<td>last_login</td>
<td>timestamp</td>
<td>YES</td>
<td></td>
<td>NULL</td>
<td></td>
</tr>
<tr>
<td>first_name</td>
<td>varchar(255)</td>
<td>YES</td>
<td></td>
<td>NULL</td>
<td></td>
</tr>
<tr>
<td>last_name</td>
<td>varchar(255)</td>
<td>YES</td>
<td></td>
<td>NULL</td>
<td></td>
</tr>
<tr>
<td>created_at</td>
<td>timestamp</td>
<td>NO</td>
<td></td>
<td>0000-00-00 00:00:00</td>
<td></td>
</tr>
<tr>
<td>updated_at</td>
<td>timestamp</td>
<td>NO</td>
<td></td>
<td>0000-00-00 00:00:00</td>
</tr>
</tbody>
</table>
```

The last row (tr) has only 5 cells  (td's) ...

### PR DESCRIPTION
**Pull request by icm7216**
Fix this issue. In the table cell does not display if bottom right corner of the table cell is empty.
This fix #188, fix #476, fix #693, and fix atom/markdown-preview#206
# before the fix

before_fix
# after the fix

after_fix

### CODE REVIEW

**Comment by DoumanAsh** [comment]
Glad to see that someone already fixed :)
Sad that i didn't find it before i started to look into it...

**Comment by DanielSmedegaardBuus** [comment]
Why isn't this merged? It's been over 18 months :D

**Comment by DanielSmedegaardBuus** [comment]
Thanks, @icm7216 !

Since this doesn't seem to be merged anytime soon, I forked marked and merged it into [my own fork](https://github.com/DanielSmedegaardBuus/marked).

**Comment by redfast00** [comment]
Can this or #357 be merged? :D

**Comment by joshbruce** [comment]
#980

**Comment by icm7216** [comment]
This issue seems to be solved by #1245. My PR is no longer needed. Thanks everyone.

marked_gfm_table

**Pull request closed without merging**
