### PR TITLE
[WIP]: Update contributing

### PR DESCRIPTION
**Pull request by joshbruce**
**Marked version:** 0.3.19

**Markdown flavor:** n/a

## Description

Update contributing file with description of Marked architecture and other helpful tidbits for contributing to the project.

## Contributor

- [ ] Test(s) exist to ensure functionality and minimize regresstion (if no tests added, list tests covering this PR); or,
- [x] no tests required for this PR.
- [ ] If submitting new feature, it has been documented in the appropriate places.

## Committer

In most cases, this should be a different person than the contributor.

- [ ] Draft GitHub release notes have been updated.
- [ ] CI is green (no forced merge required).
- [ ] Merge PR

### CODE REVIEW

**Comment by joshbruce** [comment]
@UziTech: Wondering if we should have more detailed descriptions for the various `test` scripts in `package.json`. Thoughts?

**Comment by davisjam** [comment]
I agree with @UziTech.

**Comment by joshbruce** [comment]
I tend to agree as well. Having said that, I'm not sure these things will change that much. The concept of putting them here was to begin teasing out the current architecture for other contributors; namely @intcreator.

I will start submitting refactoring PRs with minor code changes and updated comments. We could also run something like TypeDoc over the library to help generate more complete documentation. Tagging @styfle for that one.

**Comment by joshbruce** [comment]
@styfle: I only mentioned typedoc as a "sorta like" notion - not a specific solution. This PR will most likely get scaled back.

Putting the comments in the code itself will take a bit longer and involved more PRs. Leaving this one alive primarily for the new `npm` scripts.

**Comment by styfle** [comment]
@joshbruce Why not close this PR and create a new one with only the changes that are necessary?

**Comment by joshbruce** [comment]
Honestly? Having it open just made it easy for me to pull up as a reference while submitting the other PRs and I'm not sure what would be left. @UziTech is better equipped to capture a description of each of the `test` npm scripts.

**Pull request closed without merging**
